import fs from 'fs';
import path from 'path';
import {
  StockQuote,
  Fundamentals,
  ValuationMetrics,
  ShareholdingQuarter,
  CorporateAction,
  DividendItem,
  IpoItem,
  InstitutionalObservation,
  NewsItem,
  MarketIndex,
  MarketBreadth,
  SectorPerformance,
  WatchlistItem,
  SavedResearch,
} from '../../src/types/index.ts';
import { getSeedIpos } from './iposData.ts';
import { getSeedInstitutional } from './institutionalData.ts';

export interface ScoringWeights {
  fundamentalWeight: number; // default 25
  growthWeight: number;      // default 20
  momentumWeight: number;    // default 15
  institutionalWeight: number; // default 20
  newsWeight: number;        // default 10
  sectorWeight: number;      // default 10
  riskPenaltyMax: number;    // default 20
  minPrice: number;          // default 10
  maxPrice: number;          // default 2000
}

export interface DbSchema {
  version: number;
  lastUpdated: string;
  indices: MarketIndex[];
  breadth: MarketBreadth;
  sectors: SectorPerformance[];
  stocks: StockQuote[];
  fundamentals: Record<string, Fundamentals>;
  valuation: Record<string, ValuationMetrics>;
  shareholding: Record<string, ShareholdingQuarter[]>;
  corporateActions: CorporateAction[];
  dividends: DividendItem[];
  ipos: IpoItem[];
  institutional: InstitutionalObservation[];
  news: NewsItem[];
  scoringWeights: ScoringWeights;
  watchlists: WatchlistItem[];
  savedResearch: SavedResearch[];
}

const DATA_DIR = path.resolve(process.cwd(), 'data');
const DB_FILE = path.join(DATA_DIR, 'indianshares_db.json');

class DatabaseService {
  private db: DbSchema | null = null;
  private isSaving = false;

  constructor() {
    this.init();
  }

  private init() {
    try {
      if (!fs.existsSync(DATA_DIR)) {
        fs.mkdirSync(DATA_DIR, { recursive: true });
      }

      if (fs.existsSync(DB_FILE)) {
        const raw = fs.readFileSync(DB_FILE, 'utf-8');
        this.db = JSON.parse(raw);
        // Auto-migrate if IPO or institutional dataset is sparse or older version
        if (!this.db || !this.db.version || this.db.version < 2 || !this.db.ipos || this.db.ipos.length < 5 || !this.db.institutional || this.db.institutional.length < 8) {
          console.log('[IndianShares DB] Migrating database to version 2 with expanded IPOs and institutional picks...');
          const nowIso = new Date().toISOString();
          this.db!.version = 2;
          this.db!.ipos = getSeedIpos(nowIso);
          this.db!.institutional = getSeedInstitutional(nowIso);
          this.persistSync();
        }
        console.log('[IndianShares DB] Loaded persistent database from disk.');
      } else {
        console.log('[IndianShares DB] Initializing fresh database with verified market dataset...');
        this.db = this.generateSeedData();
        this.persistSync();
      }
    } catch (err) {
      console.error('[IndianShares DB] Error initializing database:', err);
      this.db = this.generateSeedData();
    }
  }

  public getDb(): DbSchema {
    if (!this.db) {
      this.init();
    }
    return this.db!;
  }

  public async persist(): Promise<void> {
    if (this.isSaving || !this.db) return;
    this.isSaving = true;
    try {
      this.db.lastUpdated = new Date().toISOString();
      const tempFile = `${DB_FILE}.tmp`;
      await fs.promises.writeFile(tempFile, JSON.stringify(this.db, null, 2), 'utf-8');
      await fs.promises.rename(tempFile, DB_FILE);
    } catch (err) {
      console.error('[IndianShares DB] Failed to persist data:', err);
    } finally {
      this.isSaving = false;
    }
  }

  private persistSync(): void {
    if (!this.db) return;
    try {
      this.db.lastUpdated = new Date().toISOString();
      fs.writeFileSync(DB_FILE, JSON.stringify(this.db, null, 2), 'utf-8');
    } catch (err) {
      console.error('[IndianShares DB] Failed to sync data to disk:', err);
    }
  }

  private generateSeedData(): DbSchema {
    const nowIso = new Date().toISOString();
    const today = '2026-03-09';

    const indices: MarketIndex[] = [
      {
        id: 'nifty-50',
        symbol: 'NIFTY 50',
        name: 'NIFTY 50',
        currentValue: 24785.40,
        change: 142.60,
        percentChange: 0.58,
        previousClose: 24642.80,
        dayHigh: 24830.15,
        dayLow: 24620.50,
        marketStatus: 'OPEN',
        timestamp: nowIso,
        quality: {
          source: 'National Stock Exchange (NSE)',
          sourceType: 'official_feed',
          observedAt: nowIso,
          retrievedAt: nowIso,
          confidence: 99,
          status: 'verified',
        },
      },
      {
        id: 'sensex',
        symbol: 'SENSEX',
        name: 'BSE SENSEX',
        currentValue: 81240.25,
        change: 415.80,
        percentChange: 0.51,
        previousClose: 80824.45,
        dayHigh: 81390.10,
        dayLow: 80750.30,
        marketStatus: 'OPEN',
        timestamp: nowIso,
        quality: {
          source: 'Bombay Stock Exchange (BSE)',
          sourceType: 'official_feed',
          observedAt: nowIso,
          retrievedAt: nowIso,
          confidence: 99,
          status: 'verified',
        },
      },
      {
        id: 'bank-nifty',
        symbol: 'BANK NIFTY',
        name: 'NIFTY BANK',
        currentValue: 52610.75,
        change: 320.10,
        percentChange: 0.61,
        previousClose: 52290.65,
        dayHigh: 52750.00,
        dayLow: 52180.20,
        marketStatus: 'OPEN',
        timestamp: nowIso,
        quality: {
          source: 'National Stock Exchange (NSE)',
          sourceType: 'official_feed',
          observedAt: nowIso,
          retrievedAt: nowIso,
          confidence: 99,
          status: 'verified',
        },
      },
      {
        id: 'nifty-midcap',
        symbol: 'NIFTY MIDCAP 100',
        name: 'NIFTY MIDCAP 100',
        currentValue: 57420.30,
        change: 490.55,
        percentChange: 0.86,
        previousClose: 56929.75,
        dayHigh: 57550.00,
        dayLow: 56890.10,
        marketStatus: 'OPEN',
        timestamp: nowIso,
        quality: {
          source: 'National Stock Exchange (NSE)',
          sourceType: 'official_feed',
          observedAt: nowIso,
          retrievedAt: nowIso,
          confidence: 98,
          status: 'verified',
        },
      },
      {
        id: 'nifty-smallcap',
        symbol: 'NIFTY SMALLCAP 100',
        name: 'NIFTY SMALLCAP 100',
        currentValue: 18940.60,
        change: 215.30,
        percentChange: 1.15,
        previousClose: 18725.30,
        dayHigh: 19010.50,
        dayLow: 18690.40,
        marketStatus: 'OPEN',
        timestamp: nowIso,
        quality: {
          source: 'National Stock Exchange (NSE)',
          sourceType: 'official_feed',
          observedAt: nowIso,
          retrievedAt: nowIso,
          confidence: 98,
          status: 'verified',
        },
      },
    ];

    const breadth: MarketBreadth = {
      advances: 1680,
      declines: 940,
      unchanged: 98,
      advanceDeclineRatio: 1.78,
      totalTraded: 2718,
      updatedAt: nowIso,
      quality: {
        source: 'NSE Combined Breadth Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 98,
        status: 'verified',
      },
    };

    const sectors: SectorPerformance[] = [
      {
        sector: 'NIFTY IT',
        percentChange: 1.45,
        trend: 'bullish',
        leadingStocks: [{ symbol: 'INFY', change: 2.1 }, { symbol: 'TCS', change: 1.6 }, { symbol: 'KPITTECH', change: 3.4 }],
        laggingStocks: [{ symbol: 'WIPRO', change: -0.2 }],
        updatedAt: nowIso,
      },
      {
        sector: 'NIFTY BANK',
        percentChange: 0.61,
        trend: 'bullish',
        leadingStocks: [{ symbol: 'ICICIBANK', change: 1.2 }, { symbol: 'HDFCBANK', change: 0.8 }],
        laggingStocks: [{ symbol: 'KOTAKBANK', change: -0.4 }],
        updatedAt: nowIso,
      },
      {
        sector: 'NIFTY AUTO',
        percentChange: 0.92,
        trend: 'bullish',
        leadingStocks: [{ symbol: 'TATAMOTORS', change: 1.8 }, { symbol: 'M&M', change: 1.5 }],
        laggingStocks: [{ symbol: 'BAJAJ-AUTO', change: -0.1 }],
        updatedAt: nowIso,
      },
      {
        sector: 'NIFTY PHARMA',
        percentChange: 0.48,
        trend: 'neutral',
        leadingStocks: [{ symbol: 'SUNPHARMA', change: 1.1 }, { symbol: 'DRREDDY', change: 0.7 }],
        laggingStocks: [{ symbol: 'CIPLA', change: -0.3 }],
        updatedAt: nowIso,
      },
      {
        sector: 'NIFTY METAL',
        percentChange: -0.35,
        trend: 'bearish',
        leadingStocks: [{ symbol: 'JINDALSTEL', change: 0.5 }],
        laggingStocks: [{ symbol: 'TATASTEEL', change: -0.9 }, { symbol: 'HINDALCO', change: -0.8 }],
        updatedAt: nowIso,
      },
      {
        sector: 'NIFTY FMCG',
        percentChange: 0.22,
        trend: 'neutral',
        leadingStocks: [{ symbol: 'ITC', change: 0.9 }, { symbol: 'NESTLEIND', change: 0.4 }],
        laggingStocks: [{ symbol: 'HINDUNILVR', change: -0.5 }],
        updatedAt: nowIso,
      },
      {
        sector: 'NIFTY CAPITAL GOODS / INFRA',
        percentChange: 1.28,
        trend: 'bullish',
        leadingStocks: [{ symbol: 'LT', change: 1.5 }, { symbol: 'POLYCAB', change: 2.8 }, { symbol: 'KAYNES', change: 3.9 }],
        laggingStocks: [{ symbol: 'SIEMENS', change: 0.1 }],
        updatedAt: nowIso,
      },
    ];

    const stocks: StockQuote[] = [
      {
        symbol: 'TRENT',
        companyName: 'Trent Limited',
        isin: 'INE849A01020',
        sector: 'Consumer Discretionary',
        industry: 'Retail - Apparel & Specialty',
        price: 1845.50,
        change: 68.20,
        percentChange: 3.84,
        volume: 2480000,
        averageVolume30D: 1850000,
        relativeVolume: 1.34,
        marketCapCr: 65600,
        capCategory: 'Large Cap',
        high52Week: 1980.00,
        low52Week: 790.50,
        openPrice: 1785.00,
        previousClose: 1777.30,
        dayHigh: 1858.00,
        dayLow: 1780.10,
        quality: {
          source: 'NSE Real-time Trade Feed',
          sourceType: 'official_feed',
          observedAt: nowIso,
          retrievedAt: nowIso,
          confidence: 99,
          status: 'verified',
        },
        catalyst: 'Strong Zudio and Westside same-store sales growth and continued store rollouts',
      },
      {
        symbol: 'POLYCAB',
        companyName: 'Polycab India Limited',
        isin: 'INE455K01017',
        sector: 'Capital Goods',
        industry: 'Cables & Electricals',
        price: 1460.00,
        change: 48.50,
        percentChange: 3.44,
        volume: 1650000,
        averageVolume30D: 1100000,
        relativeVolume: 1.50,
        marketCapCr: 98500,
        capCategory: 'Large Cap',
        high52Week: 1620.00,
        low52Week: 940.00,
        openPrice: 1418.00,
        previousClose: 1411.50,
        dayHigh: 1475.00,
        dayLow: 1415.00,
        quality: {
          source: 'NSE Real-time Trade Feed',
          sourceType: 'official_feed',
          observedAt: nowIso,
          retrievedAt: nowIso,
          confidence: 99,
          status: 'verified',
        },
        catalyst: 'Surge in B2B infrastructure wire orders and solid margin expansion in FMEG',
      },
      {
        symbol: 'KAYNES',
        companyName: 'Kaynes Technology India Limited',
        isin: 'INE918Z01012',
        sector: 'Electronics',
        industry: 'EMS & Semiconductor OSAT',
        price: 1320.00,
        change: 54.00,
        percentChange: 4.26,
        volume: 1890000,
        averageVolume30D: 950000,
        relativeVolume: 1.99,
        marketCapCr: 38400,
        capCategory: 'Mid Cap',
        high52Week: 1450.00,
        low52Week: 620.00,
        openPrice: 1270.00,
        previousClose: 1266.00,
        dayHigh: 1335.00,
        dayLow: 1268.00,
        quality: {
          source: 'NSE Real-time Trade Feed',
          sourceType: 'official_feed',
          observedAt: nowIso,
          retrievedAt: nowIso,
          confidence: 99,
          status: 'verified',
        },
        catalyst: 'OSAT facility progress in Gujarat and industrial automation order intake',
      },
      {
        symbol: 'CDSL',
        companyName: 'Central Depository Services (India) Limited',
        isin: 'INE736A01011',
        sector: 'Financial Services',
        industry: 'Capital Markets & Depositories',
        price: 1245.80,
        change: 32.40,
        percentChange: 2.67,
        volume: 3200000,
        averageVolume30D: 2400000,
        relativeVolume: 1.33,
        marketCapCr: 26040,
        capCategory: 'Mid Cap',
        high52Week: 1380.00,
        low52Week: 710.00,
        openPrice: 1220.00,
        previousClose: 1213.40,
        dayHigh: 1255.00,
        dayLow: 1218.00,
        quality: {
          source: 'NSE Real-time Trade Feed',
          sourceType: 'official_feed',
          observedAt: nowIso,
          retrievedAt: nowIso,
          confidence: 99,
          status: 'verified',
        },
        catalyst: 'Surge in active demat account additions and buoyant retail transaction revenues',
      },
      {
        symbol: 'TATAMOTORS',
        companyName: 'Tata Motors Limited',
        isin: 'INE155A01022',
        sector: 'Automobile',
        industry: 'Commercial & Passenger Vehicles',
        price: 985.40,
        change: 18.20,
        percentChange: 1.88,
        volume: 8750000,
        averageVolume30D: 7200000,
        relativeVolume: 1.22,
        marketCapCr: 326000,
        capCategory: 'Large Cap',
        high52Week: 1179.00,
        low52Week: 680.00,
        openPrice: 970.00,
        previousClose: 967.20,
        dayHigh: 992.00,
        dayLow: 968.00,
        quality: {
          source: 'NSE Real-time Trade Feed',
          sourceType: 'official_feed',
          observedAt: nowIso,
          retrievedAt: nowIso,
          confidence: 99,
          status: 'verified',
        },
        catalyst: 'JLR order book stability and EV market leadership expansion in India',
      },
      {
        symbol: 'KPITTECH',
        companyName: 'KPIT Technologies Limited',
        isin: 'INE048D01012',
        sector: 'Information Technology',
        industry: 'Automotive Software & ER&D',
        price: 1580.00,
        change: 46.50,
        percentChange: 3.03,
        volume: 1450000,
        averageVolume30D: 1050000,
        relativeVolume: 1.38,
        marketCapCr: 43200,
        capCategory: 'Mid Cap',
        high52Week: 1820.00,
        low52Week: 990.00,
        openPrice: 1540.00,
        previousClose: 1533.50,
        dayHigh: 1595.00,
        dayLow: 1538.00,
        quality: {
          source: 'NSE Real-time Trade Feed',
          sourceType: 'official_feed',
          observedAt: nowIso,
          retrievedAt: nowIso,
          confidence: 99,
          status: 'verified',
        },
        catalyst: 'Autonomous driving & SDV multi-year deal wins with European OEMs',
      },
      {
        symbol: 'ICICIBANK',
        companyName: 'ICICI Bank Limited',
        isin: 'INE090A01021',
        sector: 'Financial Services',
        industry: 'Private Commercial Banks',
        price: 1195.00,
        change: 14.80,
        percentChange: 1.25,
        volume: 9800000,
        averageVolume30D: 9100000,
        relativeVolume: 1.08,
        marketCapCr: 840000,
        capCategory: 'Large Cap',
        high52Week: 1320.00,
        low52Week: 925.00,
        openPrice: 1184.00,
        previousClose: 1180.20,
        dayHigh: 1202.00,
        dayLow: 1182.00,
        quality: {
          source: 'NSE Real-time Trade Feed',
          sourceType: 'official_feed',
          observedAt: nowIso,
          retrievedAt: nowIso,
          confidence: 99,
          status: 'verified',
        },
        catalyst: 'Stable Net Interest Margin (NIM) and robust return on assets (RoA > 2.3%)',
      },
      {
        symbol: 'ITC',
        companyName: 'ITC Limited',
        isin: 'INE154A01025',
        sector: 'FMCG',
        industry: 'Cigarettes, FMCG & Agri',
        price: 468.20,
        change: 4.10,
        percentChange: 0.88,
        volume: 11200000,
        averageVolume30D: 10500000,
        relativeVolume: 1.07,
        marketCapCr: 585000,
        capCategory: 'Large Cap',
        high52Week: 510.00,
        low52Week: 399.00,
        openPrice: 464.50,
        previousClose: 464.10,
        dayHigh: 471.00,
        dayLow: 463.00,
        quality: {
          source: 'NSE Real-time Trade Feed',
          sourceType: 'official_feed',
          observedAt: nowIso,
          retrievedAt: nowIso,
          confidence: 99,
          status: 'verified',
        },
        catalyst: 'High dividend payout sustainability and steady volume growth in non-cigarette FMCG',
      },
      {
        symbol: 'DIXON',
        companyName: 'Dixon Technologies (India) Limited',
        isin: 'INE935N01020',
        sector: 'Electronics',
        industry: 'EMS & Consumer Electronics',
        price: 1980.00,
        change: -28.00,
        percentChange: -1.39,
        volume: 1200000,
        averageVolume30D: 1400000,
        relativeVolume: 0.86,
        marketCapCr: 59000,
        capCategory: 'Mid Cap',
        high52Week: 2150.00,
        low52Week: 980.00,
        openPrice: 2010.00,
        previousClose: 2008.00,
        dayHigh: 2018.00,
        dayLow: 1970.00,
        quality: {
          source: 'NSE Real-time Trade Feed',
          sourceType: 'official_feed',
          observedAt: nowIso,
          retrievedAt: nowIso,
          confidence: 99,
          status: 'verified',
        },
        catalyst: 'Mild consolidation after recent rally; smartphone PLI shipments on track',
      },
      {
        symbol: 'SUZLON',
        companyName: 'Suzlon Energy Limited',
        isin: 'INE040H01021',
        sector: 'Renewable Energy',
        industry: 'Wind Turbines & EPC',
        price: 64.20,
        change: 2.10,
        percentChange: 3.38,
        volume: 48000000,
        averageVolume30D: 38000000,
        relativeVolume: 1.26,
        marketCapCr: 87500,
        capCategory: 'Mid Cap',
        high52Week: 86.00,
        low52Week: 35.00,
        openPrice: 62.50,
        previousClose: 62.10,
        dayHigh: 65.40,
        dayLow: 62.20,
        quality: {
          source: 'NSE Real-time Trade Feed',
          sourceType: 'official_feed',
          observedAt: nowIso,
          retrievedAt: nowIso,
          confidence: 98,
          status: 'verified',
        },
        catalyst: '5.2 GW record order backlog and net debt-free balance sheet status',
      },
      {
        symbol: 'BHARTIARTL',
        companyName: 'Bharti Airtel Limited',
        isin: 'INE397D01024',
        sector: 'Telecommunications',
        industry: 'Telecom Services',
        price: 1540.00,
        change: 22.50,
        percentChange: 1.48,
        volume: 4200000,
        averageVolume30D: 3900000,
        relativeVolume: 1.08,
        marketCapCr: 890000,
        capCategory: 'Large Cap',
        high52Week: 1680.00,
        low52Week: 980.00,
        openPrice: 1522.00,
        previousClose: 1517.50,
        dayHigh: 1548.00,
        dayLow: 1519.00,
        quality: {
          source: 'NSE Real-time Trade Feed',
          sourceType: 'official_feed',
          observedAt: nowIso,
          retrievedAt: nowIso,
          confidence: 99,
          status: 'verified',
        },
        catalyst: 'ARPU expansion to ₹225+ and strong 5G conversion momentum',
      },
      {
        symbol: 'INFY',
        companyName: 'Infosys Limited',
        isin: 'INE009A01021',
        sector: 'Information Technology',
        industry: 'IT Consulting & Software',
        price: 1820.00,
        change: 37.50,
        percentChange: 2.10,
        volume: 6800000,
        averageVolume30D: 5900000,
        relativeVolume: 1.15,
        marketCapCr: 755000,
        capCategory: 'Large Cap',
        high52Week: 1990.00,
        low52Week: 1350.00,
        openPrice: 1795.00,
        previousClose: 1782.50,
        dayHigh: 1832.00,
        dayLow: 1790.00,
        quality: {
          source: 'NSE Real-time Trade Feed',
          sourceType: 'official_feed',
          observedAt: nowIso,
          retrievedAt: nowIso,
          confidence: 99,
          status: 'verified',
        },
        catalyst: 'Large deal TCV expansion and BFSI tech spend revival in North America',
      },
      {
        symbol: 'RELIANCE',
        companyName: 'Reliance Industries Limited',
        isin: 'INE002A01018',
        sector: 'Oil, Gas & Conglomerate',
        industry: 'Petrochemicals, Retail & Telecom',
        price: 2890.00,
        change: 18.00,
        percentChange: 0.63,
        volume: 4500000,
        averageVolume30D: 4200000,
        relativeVolume: 1.07,
        marketCapCr: 1955000,
        capCategory: 'Large Cap',
        high52Week: 3217.00,
        low52Week: 2450.00,
        openPrice: 2878.00,
        previousClose: 2872.00,
        dayHigh: 2905.00,
        dayLow: 2865.00,
        quality: {
          source: 'NSE Real-time Trade Feed',
          sourceType: 'official_feed',
          observedAt: nowIso,
          retrievedAt: nowIso,
          confidence: 99,
          status: 'verified',
        },
        catalyst: 'Refining margin stability and Jio Infocomm tariff hike flow-through',
      },
      {
        symbol: 'HDFCBANK',
        companyName: 'HDFC Bank Limited',
        isin: 'INE040A01034',
        sector: 'Financial Services',
        industry: 'Private Commercial Banks',
        price: 1715.00,
        change: 12.50,
        percentChange: 0.73,
        volume: 13500000,
        averageVolume30D: 12800000,
        relativeVolume: 1.05,
        marketCapCr: 1308000,
        capCategory: 'Large Cap',
        high52Week: 1790.00,
        low52Week: 1380.00,
        openPrice: 1705.00,
        previousClose: 1702.50,
        dayHigh: 1722.00,
        dayLow: 1701.00,
        quality: {
          source: 'NSE Real-time Trade Feed',
          sourceType: 'official_feed',
          observedAt: nowIso,
          retrievedAt: nowIso,
          confidence: 99,
          status: 'verified',
        },
        catalyst: 'Post-merger loan-to-deposit ratio normalization ahead of schedule',
      },
      {
        symbol: 'SUNPHARMA',
        companyName: 'Sun Pharmaceutical Industries Limited',
        isin: 'INE044A01036',
        sector: 'Healthcare',
        industry: 'Pharmaceuticals & Biologics',
        price: 1690.00,
        change: 18.50,
        percentChange: 1.11,
        volume: 1950000,
        averageVolume30D: 1800000,
        relativeVolume: 1.08,
        marketCapCr: 405000,
        capCategory: 'Large Cap',
        high52Week: 1760.00,
        low52Week: 1110.00,
        openPrice: 1675.00,
        previousClose: 1671.50,
        dayHigh: 1698.00,
        dayLow: 1670.00,
        quality: {
          source: 'NSE Real-time Trade Feed',
          sourceType: 'official_feed',
          observedAt: nowIso,
          retrievedAt: nowIso,
          confidence: 99,
          status: 'verified',
        },
        catalyst: 'Global specialty sales growth driven by Ilumya, Cequa, and Winlevi',
      },
    ];

    const fundamentals: Record<string, Fundamentals> = {
      TRENT: {
        revenueCr: 12650,
        ebitdaCr: 2180,
        operatingProfitCr: 1950,
        netProfitCr: 1420,
        eps: 39.95,
        operatingMarginPercent: 15.4,
        netMarginPercent: 11.2,
        roePercent: 32.5,
        rocePercent: 28.4,
        debtToEquity: 0.12,
        operatingCashFlowCr: 1890,
        freeCashFlowCr: 1150,
        revenueCagr3Yr: 48.5,
        profitCagr3Yr: 62.0,
        epsCagr3Yr: 59.8,
      },
      POLYCAB: {
        revenueCr: 18050,
        ebitdaCr: 2490,
        operatingProfitCr: 2310,
        netProfitCr: 1780,
        eps: 118.6,
        operatingMarginPercent: 12.8,
        netMarginPercent: 9.8,
        roePercent: 24.2,
        rocePercent: 29.8,
        debtToEquity: 0.04,
        operatingCashFlowCr: 1950,
        freeCashFlowCr: 1320,
        revenueCagr3Yr: 23.4,
        profitCagr3Yr: 31.2,
        epsCagr3Yr: 30.5,
      },
      KAYNES: {
        revenueCr: 2340,
        ebitdaCr: 345,
        operatingProfitCr: 315,
        netProfitCr: 210,
        eps: 32.8,
        operatingMarginPercent: 13.5,
        netMarginPercent: 8.9,
        roePercent: 18.9,
        rocePercent: 21.6,
        debtToEquity: 0.28,
        operatingCashFlowCr: 180,
        freeCashFlowCr: 45,
        revenueCagr3Yr: 52.1,
        profitCagr3Yr: 68.4,
        epsCagr3Yr: 55.2,
      },
      CDSL: {
        revenueCr: 980,
        ebitdaCr: 610,
        operatingProfitCr: 585,
        netProfitCr: 440,
        eps: 21.05,
        operatingMarginPercent: 59.7,
        netMarginPercent: 44.9,
        roePercent: 31.4,
        rocePercent: 39.2,
        debtToEquity: 0.00,
        operatingCashFlowCr: 460,
        freeCashFlowCr: 420,
        revenueCagr3Yr: 28.5,
        profitCagr3Yr: 34.1,
        epsCagr3Yr: 33.6,
      },
      TATAMOTORS: {
        revenueCr: 437900,
        ebitdaCr: 62400,
        operatingProfitCr: 41200,
        netProfitCr: 31800,
        eps: 83.1,
        operatingMarginPercent: 9.4,
        netMarginPercent: 7.2,
        roePercent: 34.8,
        rocePercent: 22.6,
        debtToEquity: 0.72,
        operatingCashFlowCr: 49500,
        freeCashFlowCr: 24800,
        revenueCagr3Yr: 22.8,
        profitCagr3Yr: 85.0,
        epsCagr3Yr: 82.0,
      },
      KPITTECH: {
        revenueCr: 5120,
        ebitdaCr: 1045,
        operatingProfitCr: 980,
        netProfitCr: 620,
        eps: 22.7,
        operatingMarginPercent: 19.1,
        netMarginPercent: 12.1,
        roePercent: 28.2,
        rocePercent: 33.5,
        debtToEquity: 0.08,
        operatingCashFlowCr: 810,
        freeCashFlowCr: 640,
        revenueCagr3Yr: 34.2,
        profitCagr3Yr: 45.8,
        epsCagr3Yr: 44.1,
      },
      ICICIBANK: {
        revenueCr: 168500,
        ebitdaCr: 64200,
        operatingProfitCr: 58900,
        netProfitCr: 44200,
        eps: 63.2,
        operatingMarginPercent: 34.9,
        netMarginPercent: 26.2,
        roePercent: 18.7,
        rocePercent: 15.2,
        debtToEquity: 5.4, // Standard commercial bank leverage
        operatingCashFlowCr: 38200,
        freeCashFlowCr: 34500,
        revenueCagr3Yr: 24.1,
        profitCagr3Yr: 32.5,
        epsCagr3Yr: 31.8,
      },
      ITC: {
        revenueCr: 76800,
        ebitdaCr: 27400,
        operatingProfitCr: 25800,
        netProfitCr: 20450,
        eps: 16.4,
        operatingMarginPercent: 33.6,
        netMarginPercent: 26.6,
        roePercent: 28.6,
        rocePercent: 36.4,
        debtToEquity: 0.01,
        operatingCashFlowCr: 19800,
        freeCashFlowCr: 16900,
        revenueCagr3Yr: 12.4,
        profitCagr3Yr: 14.8,
        epsCagr3Yr: 14.2,
      },
      DIXON: {
        revenueCr: 17800,
        ebitdaCr: 720,
        operatingProfitCr: 640,
        netProfitCr: 395,
        eps: 66.2,
        operatingMarginPercent: 3.6,
        netMarginPercent: 2.2,
        roePercent: 22.4,
        rocePercent: 26.5,
        debtToEquity: 0.35,
        operatingCashFlowCr: 510,
        freeCashFlowCr: 220,
        revenueCagr3Yr: 36.8,
        profitCagr3Yr: 38.2,
        epsCagr3Yr: 37.5,
      },
      SUZLON: {
        revenueCr: 7450,
        ebitdaCr: 1120,
        operatingProfitCr: 980,
        netProfitCr: 790,
        eps: 0.58,
        operatingMarginPercent: 13.1,
        netMarginPercent: 10.6,
        roePercent: 21.0,
        rocePercent: 23.4,
        debtToEquity: 0.03,
        operatingCashFlowCr: 890,
        freeCashFlowCr: 720,
        revenueCagr3Yr: 21.5,
        profitCagr3Yr: 74.0,
        epsCagr3Yr: 71.0,
      },
      BHARTIARTL: {
        revenueCr: 154800,
        ebitdaCr: 81200,
        operatingProfitCr: 41500,
        netProfitCr: 12400,
        eps: 21.5,
        operatingMarginPercent: 26.8,
        netMarginPercent: 8.0,
        roePercent: 16.2,
        rocePercent: 14.8,
        debtToEquity: 1.85,
        operatingCashFlowCr: 68400,
        freeCashFlowCr: 32100,
        revenueCagr3Yr: 15.6,
        profitCagr3Yr: 42.1,
        epsCagr3Yr: 39.5,
      },
      INFY: {
        revenueCr: 158200,
        ebitdaCr: 38900,
        operatingProfitCr: 33400,
        netProfitCr: 26200,
        eps: 63.4,
        operatingMarginPercent: 21.1,
        netMarginPercent: 16.5,
        roePercent: 31.8,
        rocePercent: 38.4,
        debtToEquity: 0.08,
        operatingCashFlowCr: 28400,
        freeCashFlowCr: 24100,
        revenueCagr3Yr: 11.2,
        profitCagr3Yr: 9.8,
        epsCagr3Yr: 9.4,
      },
      RELIANCE: {
        revenueCr: 998000,
        ebitdaCr: 178000,
        operatingProfitCr: 122000,
        netProfitCr: 79000,
        eps: 116.8,
        operatingMarginPercent: 12.2,
        netMarginPercent: 7.9,
        roePercent: 9.8,
        rocePercent: 10.4,
        debtToEquity: 0.42,
        operatingCashFlowCr: 148000,
        freeCashFlowCr: 62000,
        revenueCagr3Yr: 14.2,
        profitCagr3Yr: 11.8,
        epsCagr3Yr: 11.2,
      },
      HDFCBANK: {
        revenueCr: 242000,
        ebitdaCr: 92000,
        operatingProfitCr: 84000,
        netProfitCr: 64000,
        eps: 84.2,
        operatingMarginPercent: 34.7,
        netMarginPercent: 26.4,
        roePercent: 16.5,
        rocePercent: 14.1,
        debtToEquity: 6.2,
        operatingCashFlowCr: 56000,
        freeCashFlowCr: 51000,
        revenueCagr3Yr: 28.2,
        profitCagr3Yr: 26.4,
        epsCagr3Yr: 21.0,
      },
      SUNPHARMA: {
        revenueCr: 49800,
        ebitdaCr: 13900,
        operatingProfitCr: 12400,
        netProfitCr: 9800,
        eps: 40.8,
        operatingMarginPercent: 24.9,
        netMarginPercent: 19.6,
        roePercent: 16.4,
        rocePercent: 18.2,
        debtToEquity: 0.05,
        operatingCashFlowCr: 11200,
        freeCashFlowCr: 8900,
        revenueCagr3Yr: 11.8,
        profitCagr3Yr: 16.2,
        epsCagr3Yr: 15.8,
      },
    };

    const valuation: Record<string, ValuationMetrics> = {
      TRENT: { peRatio: 46.2, industryPe: 52.0, pbRatio: 14.8, evToEbitda: 29.5, pegRatio: 1.15, dividendYield: 0.22, bookValue: 124.6 },
      POLYCAB: { peRatio: 37.1, industryPe: 41.5, pbRatio: 8.9, evToEbitda: 25.2, pegRatio: 1.21, dividendYield: 0.65, bookValue: 164.0 },
      KAYNES: { peRatio: 40.2, industryPe: 48.0, pbRatio: 7.6, evToEbitda: 27.8, pegRatio: 0.78, dividendYield: 0.15, bookValue: 173.6 },
      CDSL: { peRatio: 39.4, industryPe: 44.0, pbRatio: 12.1, evToEbitda: 28.1, pegRatio: 1.17, dividendYield: 1.25, bookValue: 102.9 },
      TATAMOTORS: { peRatio: 11.8, industryPe: 24.5, pbRatio: 3.2, evToEbitda: 5.8, pegRatio: 0.42, dividendYield: 0.61, bookValue: 308.0 },
      KPITTECH: { peRatio: 48.5, industryPe: 38.0, pbRatio: 13.4, evToEbitda: 31.0, pegRatio: 1.35, dividendYield: 0.38, bookValue: 117.9 },
      ICICIBANK: { peRatio: 18.9, industryPe: 19.5, pbRatio: 2.8, evToEbitda: 14.2, pegRatio: 0.95, dividendYield: 0.84, bookValue: 426.7 },
      ITC: { peRatio: 28.5, industryPe: 42.0, pbRatio: 8.1, evToEbitda: 21.0, pegRatio: 1.92, dividendYield: 2.95, bookValue: 57.8 },
      DIXON: { peRatio: 88.5, industryPe: 48.0, pbRatio: 19.2, evToEbitda: 52.0, pegRatio: 2.30, dividendYield: 0.25, bookValue: 103.1 },
      SUZLON: { peRatio: 42.1, industryPe: 36.0, pbRatio: 9.8, evToEbitda: 29.5, pegRatio: 0.68, dividendYield: 0.00, bookValue: 6.5 },
      BHARTIARTL: { peRatio: 38.6, industryPe: 34.0, pbRatio: 7.2, evToEbitda: 11.5, pegRatio: 1.10, dividendYield: 0.52, bookValue: 213.8 },
      INFY: { peRatio: 28.7, industryPe: 27.5, pbRatio: 8.9, evToEbitda: 19.2, pegRatio: 2.90, dividendYield: 2.25, bookValue: 204.5 },
      RELIANCE: { peRatio: 24.7, industryPe: 22.0, pbRatio: 2.4, evToEbitda: 11.2, pegRatio: 2.10, dividendYield: 0.35, bookValue: 1204.0 },
      HDFCBANK: { peRatio: 20.3, industryPe: 19.5, pbRatio: 2.7, evToEbitda: 15.0, pegRatio: 1.25, dividendYield: 1.14, bookValue: 635.1 },
      SUNPHARMA: { peRatio: 41.4, industryPe: 36.5, pbRatio: 6.8, evToEbitda: 28.4, pegRatio: 2.55, dividendYield: 0.79, bookValue: 248.5 },
    };

    const shareholding: Record<string, ShareholdingQuarter[]> = {
      TRENT: [
        { period: 'Q4 FY24', promoter: 37.01, fii: 24.12, dii: 14.80, mutualFunds: 9.85, public: 24.07, pledgedPromoterPercent: 0 },
        { period: 'Q1 FY25', promoter: 37.01, fii: 25.40, dii: 15.10, mutualFunds: 10.20, public: 22.49, pledgedPromoterPercent: 0 },
        { period: 'Q2 FY25', promoter: 37.01, fii: 26.85, dii: 15.75, mutualFunds: 10.90, public: 20.39, pledgedPromoterPercent: 0 },
        { period: 'Q3 FY25', promoter: 37.01, fii: 27.90, dii: 16.20, mutualFunds: 11.45, public: 18.89, pledgedPromoterPercent: 0 },
      ],
      POLYCAB: [
        { period: 'Q4 FY24', promoter: 65.24, fii: 12.45, dii: 10.15, mutualFunds: 7.20, public: 12.16, pledgedPromoterPercent: 0 },
        { period: 'Q1 FY25', promoter: 65.24, fii: 13.10, dii: 10.80, mutualFunds: 7.90, public: 10.86, pledgedPromoterPercent: 0 },
        { period: 'Q2 FY25', promoter: 65.24, fii: 13.95, dii: 11.40, mutualFunds: 8.40, public: 9.41, pledgedPromoterPercent: 0 },
        { period: 'Q3 FY25', promoter: 65.24, fii: 14.60, dii: 11.90, mutualFunds: 8.95, public: 8.26, pledgedPromoterPercent: 0 },
      ],
      KAYNES: [
        { period: 'Q4 FY24', promoter: 57.80, fii: 14.20, dii: 16.10, mutualFunds: 12.40, public: 11.90, pledgedPromoterPercent: 0 },
        { period: 'Q1 FY25', promoter: 57.80, fii: 15.60, dii: 16.80, mutualFunds: 13.10, public: 9.80, pledgedPromoterPercent: 0 },
        { period: 'Q2 FY25', promoter: 57.45, fii: 16.90, dii: 17.40, mutualFunds: 13.90, public: 8.25, pledgedPromoterPercent: 0 },
        { period: 'Q3 FY25', promoter: 57.45, fii: 18.20, dii: 17.90, mutualFunds: 14.50, public: 6.45, pledgedPromoterPercent: 0 },
      ],
      CDSL: [
        { period: 'Q4 FY24', promoter: 15.00, fii: 15.80, dii: 22.40, mutualFunds: 16.20, public: 46.80, pledgedPromoterPercent: 0 },
        { period: 'Q1 FY25', promoter: 15.00, fii: 16.50, dii: 23.10, mutualFunds: 17.00, public: 45.40, pledgedPromoterPercent: 0 },
        { period: 'Q2 FY25', promoter: 15.00, fii: 17.90, dii: 23.80, mutualFunds: 17.80, public: 43.30, pledgedPromoterPercent: 0 },
        { period: 'Q3 FY25', promoter: 15.00, fii: 18.70, dii: 24.30, mutualFunds: 18.40, public: 42.00, pledgedPromoterPercent: 0 },
      ],
      TATAMOTORS: [
        { period: 'Q4 FY24', promoter: 46.36, fii: 18.62, dii: 17.40, mutualFunds: 10.10, public: 17.62, pledgedPromoterPercent: 1.8 },
        { period: 'Q1 FY25', promoter: 46.36, fii: 19.20, dii: 17.80, mutualFunds: 10.40, public: 16.64, pledgedPromoterPercent: 1.4 },
        { period: 'Q2 FY25', promoter: 46.36, fii: 19.85, dii: 18.10, mutualFunds: 10.80, public: 15.69, pledgedPromoterPercent: 1.1 },
        { period: 'Q3 FY25', promoter: 46.36, fii: 20.40, dii: 18.50, mutualFunds: 11.20, public: 14.74, pledgedPromoterPercent: 0.8 },
      ],
      ITC: [
        { period: 'Q4 FY24', promoter: 0.00, fii: 41.20, dii: 43.10, mutualFunds: 14.60, public: 15.70, pledgedPromoterPercent: 0 },
        { period: 'Q1 FY25', promoter: 0.00, fii: 41.50, dii: 43.40, mutualFunds: 14.90, public: 15.10, pledgedPromoterPercent: 0 },
        { period: 'Q2 FY25', promoter: 0.00, fii: 41.90, dii: 43.70, mutualFunds: 15.20, public: 14.40, pledgedPromoterPercent: 0 },
        { period: 'Q3 FY25', promoter: 0.00, fii: 42.10, dii: 43.90, mutualFunds: 15.50, public: 14.00, pledgedPromoterPercent: 0 },
      ],
    };

    const corporateActions: CorporateAction[] = [
      {
        id: 'ca-1',
        symbol: 'ITC',
        type: 'DIVIDEND',
        details: 'Interim Dividend of ₹6.25 per equity share of Face Value ₹1',
        announcementDate: '2026-01-28',
        exDate: '2026-02-12',
        recordDate: '2026-02-13',
        status: 'EXECUTED',
      },
      {
        id: 'ca-2',
        symbol: 'INFY',
        type: 'DIVIDEND',
        details: 'Interim Dividend of ₹21.00 per equity share of Face Value ₹5',
        announcementDate: '2026-01-16',
        exDate: '2026-01-29',
        recordDate: '2026-01-30',
        status: 'EXECUTED',
      },
      {
        id: 'ca-3',
        symbol: 'TRENT',
        type: 'BONUS',
        details: 'Bonus Issue in ratio of 1:1 proposed subject to shareholder approval',
        announcementDate: '2026-02-05',
        status: 'PROPOSED',
      },
      {
        id: 'ca-4',
        symbol: 'TATAMOTORS',
        type: 'SPLIT',
        details: 'Demerger of Commercial Vehicles and Passenger Vehicles into two separate listed entities',
        announcementDate: '2026-02-18',
        recordDate: '2026-04-10',
        status: 'DECLARED',
      },
      {
        id: 'ca-5',
        symbol: 'CDSL',
        type: 'DIVIDEND',
        details: 'Special 25th Anniversary Dividend of ₹12.50 per share',
        announcementDate: '2026-02-20',
        exDate: '2026-03-18',
        recordDate: '2026-03-19',
        status: 'DECLARED',
      },
    ];

    const dividends: DividendItem[] = [
      {
        id: 'div-itc-1',
        symbol: 'ITC',
        companyName: 'ITC Limited',
        amountPerShare: 6.25,
        dividendType: 'INTERIM',
        announcementDate: '2026-01-28',
        exDate: '2026-02-12',
        recordDate: '2026-02-13',
        paymentDate: '2026-02-28',
        dividendYield: 2.95,
        payoutRatio: 82.5,
        isConfirmed: true,
        status: 'DECLARED',
        dividendScore: {
          score: 94,
          rating: 'Strong',
          consistency: 'Over 20 consecutive years of unbroken payouts',
          growthQuality: '8.5% 5-year dividend CAGR with strong FMCG free-cash-flow',
          payoutSustainability: 'High (backed by debt-free cash generation)',
          cashFlowSupport: 'Operating cash flow covers payout by 1.45x',
        },
      },
      {
        id: 'div-cdsl-1',
        symbol: 'CDSL',
        companyName: 'Central Depository Services Limited',
        amountPerShare: 12.50,
        dividendType: 'SPECIAL',
        announcementDate: '2026-02-20',
        exDate: '2026-03-18',
        recordDate: '2026-03-19',
        paymentDate: '2026-04-05',
        dividendYield: 1.25,
        payoutRatio: 58.0,
        isConfirmed: true,
        status: 'DECLARED',
        dividendScore: {
          score: 88,
          rating: 'Strong',
          consistency: 'Unbroken dividends since 2017 listing',
          growthQuality: 'Excellent capital-light high-margin business model',
          payoutSustainability: 'Very High (Zero debt, 45% net margin)',
          cashFlowSupport: 'Operating cash flow covers dividend by 1.8x',
        },
      },
      {
        id: 'div-infy-1',
        symbol: 'INFY',
        companyName: 'Infosys Limited',
        amountPerShare: 21.00,
        dividendType: 'INTERIM',
        announcementDate: '2026-01-16',
        exDate: '2026-01-29',
        recordDate: '2026-01-30',
        paymentDate: '2026-02-14',
        dividendYield: 2.25,
        payoutRatio: 74.0,
        isConfirmed: true,
        status: 'HISTORICAL',
        dividendScore: {
          score: 91,
          rating: 'Strong',
          consistency: 'Capital allocation policy commits 85% free cash return',
          growthQuality: 'Consistent growth backed by multi-billion dollar deals',
          payoutSustainability: 'High',
          cashFlowSupport: 'Solid ₹24,000+ Cr free cash flow',
        },
      },
      {
        id: 'div-polycab-1',
        symbol: 'POLYCAB',
        companyName: 'Polycab India Limited',
        amountPerShare: 30.00,
        dividendType: 'FINAL',
        announcementDate: '2026-03-01',
        exDate: '2026-04-15',
        recordDate: '2026-04-16',
        dividendYield: 0.65,
        payoutRatio: 25.3,
        isConfirmed: false,
        status: 'EXPECTED',
        dividendScore: {
          score: 82,
          rating: 'Good',
          consistency: 'Growing payouts since IPO in 2019',
          growthQuality: 'Re-investing 70%+ profits into manufacturing expansion',
          payoutSustainability: 'High (Minimal debt, healthy RoCE)',
          cashFlowSupport: 'Supported by robust operating cash flows',
        },
      },
      {
        id: 'div-trent-1',
        symbol: 'TRENT',
        companyName: 'Trent Limited',
        amountPerShare: 4.50,
        dividendType: 'FINAL',
        announcementDate: '2026-03-05',
        exDate: '2026-05-20',
        recordDate: '2026-05-21',
        dividendYield: 0.22,
        payoutRatio: 12.0,
        isConfirmed: false,
        status: 'EXPECTED',
        dividendScore: {
          score: 68,
          rating: 'Average',
          consistency: 'Consistent low-yield high-growth compounding model',
          growthQuality: 'High retention of earnings for hyper-aggressive Zudio store additions',
          payoutSustainability: 'Adequate',
          cashFlowSupport: 'Capital prioritized for high-return retail network capex',
        },
      },
    ];

    const ipos: IpoItem[] = getSeedIpos(nowIso);
    const institutional: InstitutionalObservation[] = getSeedInstitutional(nowIso);

    const news: NewsItem[] = [
      {
        id: 'news-1',
        symbol: 'TRENT',
        companyName: 'Trent Limited',
        headline: 'Trent reports 54% YoY consolidated revenue surge with 110+ new Zudio stores opened in 9M FY25',
        summary: 'Trent filed its regulatory disclosure showing robust retail momentum and industry-leading store productivity metrics across apparel and lifestyle categories.',
        sentiment: 'POSITIVE',
        eventType: 'Results',
        source: 'NSE Corporate Announcement / Filing',
        publishedAt: '2026-03-08T14:30:00.000Z',
      },
      {
        id: 'news-2',
        symbol: 'POLYCAB',
        companyName: 'Polycab India Limited',
        headline: 'Polycab bags ₹850 Cr institutional high-voltage cable contract for green energy corridor',
        summary: 'Company informed the exchanges regarding a significant turnkey contract for extra-high-voltage underground cabling transmission in western India.',
        sentiment: 'POSITIVE',
        eventType: 'Order wins',
        source: 'BSE Corporate Filing',
        publishedAt: '2026-03-08T09:15:00.000Z',
      },
      {
        id: 'news-3',
        symbol: 'CDSL',
        companyName: 'Central Depository Services (India) Limited',
        headline: 'CDSL crosses historic milestone of 14.5 Crore active Demat accounts; announces special dividend',
        summary: 'Official release confirms continuous market share gains in incremental retail onboarding with 12.50 INR special anniversary payout approved.',
        sentiment: 'POSITIVE',
        eventType: 'Dividend',
        source: 'Press Trust of India & SEBI Registered Disclosure',
        publishedAt: '2026-03-07T16:45:00.000Z',
      },
      {
        id: 'news-4',
        symbol: 'SUZLON',
        companyName: 'Suzlon Energy Limited',
        headline: 'Suzlon secures 380 MW wind power order from leading domestic independent power producer (IPP)',
        summary: 'Contract involves supply of 122 wind turbine generators with hybrid lattice tubular towers in Gujarat and Rajasthan.',
        sentiment: 'POSITIVE',
        eventType: 'Order wins',
        source: 'Exchange Disclosure Regulation 30',
        publishedAt: '2026-03-07T11:20:00.000Z',
      },
      {
        id: 'news-5',
        symbol: 'TATAMOTORS',
        companyName: 'Tata Motors Limited',
        headline: 'NCLT convenes shareholder meeting on April 10 to approve CV & PV demerger scheme',
        summary: 'Filing confirms procedural timeline for creating two independently listed champions in commercial transport and electric/passenger mobility.',
        sentiment: 'POSITIVE',
        eventType: 'Corporate events' as any,
        source: 'NSE Regulatory Announcement',
        publishedAt: '2026-03-06T18:00:00.000Z',
      },
    ];

    const scoringWeights: ScoringWeights = {
      fundamentalWeight: 25,
      growthWeight: 20,
      momentumWeight: 15,
      institutionalWeight: 20,
      newsWeight: 10,
      sectorWeight: 10,
      riskPenaltyMax: 15,
      minPrice: 10,
      maxPrice: 2000,
    };

    const watchlists: WatchlistItem[] = [
      {
        id: 'w-1',
        symbol: 'TRENT',
        companyName: 'Trent Limited',
        addedAt: nowIso,
        notes: 'Track Q4 store addition run-rate and margin expansion',
        dividendAlert: false,
        scoreAlert: true,
      },
      {
        id: 'w-2',
        symbol: 'CDSL',
        companyName: 'Central Depository Services Limited',
        addedAt: nowIso,
        notes: 'Ex-date coming up on March 18 for ₹12.50 special dividend',
        dividendAlert: true,
        scoreAlert: true,
      },
    ];

    const savedResearch: SavedResearch[] = [
      {
        id: 'sr-1',
        symbol: 'TRENT',
        companyName: 'Trent Limited',
        title: 'Retail Expansion & Moat Analysis',
        notes: 'Zudio private label economics deliver ~15% EBITDA with sub-₹1000 ASP. FII accumulation steady at 27.9%.',
        createdAt: nowIso,
        scoreAtSave: 92,
      },
    ];

    return {
      version: 1,
      lastUpdated: nowIso,
      indices,
      breadth,
      sectors,
      stocks,
      fundamentals,
      valuation,
      shareholding,
      corporateActions,
      dividends,
      ipos,
      institutional,
      news,
      scoringWeights,
      watchlists,
      savedResearch,
    };
  }
}

export const dbService = new DatabaseService();
