import { DividendItem } from '../../src/types/index.ts';

export function getSeedDividends(nowIso: string): DividendItem[] {
  return [
    {
      id: 'div-tcs-1',
      symbol: 'TCS',
      companyName: 'Tata Consultancy Services Limited',
      amountPerShare: 28.0,
      dividendType: 'INTERIM',
      announcementDate: '2024-10-10',
      exDate: '2024-10-18',
      recordDate: '2024-10-19',
      paymentDate: '2024-11-05',
      dividendYield: 1.35,
      payoutRatio: 68.4,
      isConfirmed: true,
      status: 'DECLARED',
      dividendScore: {
        score: 96,
        rating: 'Strong',
        consistency: 'Unbroken quarterly payouts since 2004 listing',
        growthQuality: '14.2% 5-year dividend CAGR returning >80% free cash flow',
        payoutSustainability: 'Extremely High (Debt-free, ₹41,800+ Cr free cash flow)',
        cashFlowSupport: 'Operating cash flow covers dividend by 1.9x',
      },
    },
    {
      id: 'div-infy-1',
      symbol: 'INFY',
      companyName: 'Infosys Limited',
      amountPerShare: 21.0,
      dividendType: 'INTERIM',
      announcementDate: '2024-10-17',
      exDate: '2024-10-29',
      recordDate: '2024-10-29',
      paymentDate: '2024-11-08',
      dividendYield: 2.11,
      payoutRatio: 74.2,
      isConfirmed: true,
      status: 'DECLARED',
      dividendScore: {
        score: 93,
        rating: 'Strong',
        consistency: 'Consistent biannual payouts with special distributions',
        growthQuality: 'Capital return policy mandates 85% free cash flow returned to shareholders',
        payoutSustainability: 'High (Zero debt balance sheet)',
        cashFlowSupport: 'Robust operating cash generation',
      },
    },
    {
      id: 'div-itc-1',
      symbol: 'ITC',
      companyName: 'ITC Limited',
      amountPerShare: 7.5,
      dividendType: 'FINAL',
      announcementDate: '2024-05-23',
      exDate: '2024-06-04',
      recordDate: '2024-06-04',
      paymentDate: '2024-06-28',
      dividendYield: 3.25,
      payoutRatio: 82.5,
      isConfirmed: true,
      status: 'DECLARED',
      dividendScore: {
        score: 95,
        rating: 'Strong',
        consistency: 'Over 25 consecutive years of continuous dividend growth',
        growthQuality: 'High operating cash flow from FMCG, Cigarettes, and Hotels',
        payoutSustainability: 'High (backed by zero debt and monopolistic cash flow)',
        cashFlowSupport: 'Operating cash flow covers payout by 1.45x',
      },
    },
    {
      id: 'div-coalindia-1',
      symbol: 'COALINDIA',
      companyName: 'Coal India Limited',
      amountPerShare: 15.75,
      dividendType: 'INTERIM',
      announcementDate: '2024-10-25',
      exDate: '2024-11-05',
      recordDate: '2024-11-05',
      paymentDate: '2024-11-24',
      dividendYield: 5.4,
      payoutRatio: 65.0,
      isConfirmed: true,
      status: 'DECLARED',
      dividendScore: {
        score: 92,
        rating: 'Strong',
        consistency: 'Among highest PSU dividend yielders on Dalal Street',
        growthQuality: 'Strong volumes driven by India power demand growth',
        payoutSustainability: 'High (Sovereign PSU with large cash pile)',
        cashFlowSupport: 'Very high dividend payout ratio',
      },
    },
    {
      id: 'div-vedl-1',
      symbol: 'VEDL',
      companyName: 'Vedanta Limited',
      amountPerShare: 20.0,
      dividendType: 'INTERIM',
      announcementDate: '2024-09-02',
      exDate: '2024-09-10',
      recordDate: '2024-09-10',
      paymentDate: '2024-09-28',
      dividendYield: 8.8,
      payoutRatio: 88.0,
      isConfirmed: true,
      status: 'DECLARED',
      dividendScore: {
        score: 87,
        rating: 'Good',
        consistency: 'High frequency interim payouts (up to 4-5 times per fiscal year)',
        growthQuality: 'High dividend yield play on global commodity cycles',
        payoutSustainability: 'Moderate (sensitive to global metal pricing)',
        cashFlowSupport: 'Supported by operational EBITDA',
      },
    },
    {
      id: 'div-sbin-1',
      symbol: 'SBIN',
      companyName: 'State Bank of India',
      amountPerShare: 13.7,
      dividendType: 'FINAL',
      announcementDate: '2024-05-09',
      exDate: '2024-05-22',
      recordDate: '2024-05-22',
      paymentDate: '2024-06-05',
      dividendYield: 1.42,
      payoutRatio: 22.0,
      isConfirmed: true,
      status: 'DECLARED',
      dividendScore: {
        score: 89,
        rating: 'Good',
        consistency: 'Record profit trajectory expanding dividend capacity',
        growthQuality: 'Supported by 42% 3-year profit CAGR',
        payoutSustainability: 'High (Low payout leaves capital for balance sheet growth)',
        cashFlowSupport: 'Capital adequacy comfortably above RBI norms',
      },
    },
    {
      id: 'div-hcltech-1',
      symbol: 'HCLTECH',
      companyName: 'HCL Technologies Limited',
      amountPerShare: 12.0,
      dividendType: 'INTERIM',
      announcementDate: '2024-10-14',
      exDate: '2024-10-22',
      recordDate: '2024-10-22',
      paymentDate: '2024-11-06',
      dividendYield: 2.95,
      payoutRatio: 84.0,
      isConfirmed: true,
      status: 'DECLARED',
      dividendScore: {
        score: 93,
        rating: 'Strong',
        consistency: 'Quarterly dividend policy in place for over 8 years',
        growthQuality: 'Consistent yield averaging 3%+ per year',
        payoutSustainability: 'High (Zero net debt, high IT services operating margins)',
        cashFlowSupport: 'Free cash flow fully covers dividend obligations',
      },
    },
    {
      id: 'div-lt-1',
      symbol: 'LT',
      companyName: 'Larsen & Toubro Limited',
      amountPerShare: 28.0,
      dividendType: 'FINAL',
      announcementDate: '2024-05-08',
      exDate: '2024-06-20',
      recordDate: '2024-06-20',
      paymentDate: '2024-07-15',
      dividendYield: 0.85,
      payoutRatio: 35.0,
      isConfirmed: true,
      status: 'DECLARED',
      dividendScore: {
        score: 90,
        rating: 'Strong',
        consistency: 'Decades of uninterrupted shareholder distributions',
        growthQuality: 'Backed by record ₹5.2 lakh crore EPC order backlog',
        payoutSustainability: 'Very High',
        cashFlowSupport: 'Strong operational cash generation',
      },
    },
    {
      id: 'div-cdsl-1',
      symbol: 'CDSL',
      companyName: 'Central Depository Services Limited',
      amountPerShare: 12.5,
      dividendType: 'SPECIAL',
      announcementDate: '2024-05-04',
      exDate: '2024-07-16',
      recordDate: '2024-07-16',
      paymentDate: '2024-08-02',
      dividendYield: 1.25,
      payoutRatio: 58.0,
      isConfirmed: true,
      status: 'DECLARED',
      dividendScore: {
        score: 90,
        rating: 'Strong',
        consistency: '100% track record of annual and special dividends since 2017',
        growthQuality: 'Beneficiary of explosive Indian retail demat account additions',
        payoutSustainability: 'Very High (Debt-free, 45%+ net profit margins)',
        cashFlowSupport: 'Operating cash covers distribution by 1.8x',
      },
    },
    {
      id: 'div-polycab-1',
      symbol: 'POLYCAB',
      companyName: 'Polycab India Limited',
      amountPerShare: 30.0,
      dividendType: 'FINAL',
      announcementDate: '2024-05-10',
      exDate: '2024-06-28',
      recordDate: '2024-06-28',
      paymentDate: '2024-07-18',
      dividendYield: 0.65,
      payoutRatio: 26.0,
      isConfirmed: true,
      status: 'DECLARED',
      dividendScore: {
        score: 88,
        rating: 'Good',
        consistency: 'Progressive dividend increases matching cables & wires volume growth',
        growthQuality: 'Strong domestic electrification and export demand',
        payoutSustainability: 'High (Net cash company)',
        cashFlowSupport: 'Solid balance sheet support',
      },
    },
    {
      id: 'div-sunpharma-1',
      symbol: 'SUNPHARMA',
      companyName: 'Sun Pharmaceutical Industries Limited',
      amountPerShare: 5.0,
      dividendType: 'FINAL',
      announcementDate: '2024-05-22',
      exDate: '2024-07-12',
      recordDate: '2024-07-12',
      paymentDate: '2024-07-30',
      dividendYield: 0.8,
      payoutRatio: 32.0,
      isConfirmed: true,
      status: 'DECLARED',
      dividendScore: {
        score: 89,
        rating: 'Good',
        consistency: 'Steady annual dividend distributions with high global specialty drug margins',
        growthQuality: 'Top Indian pharma franchise with expanding US specialty portfolio',
        payoutSustainability: 'High',
        cashFlowSupport: 'Robust operating cash flows',
      },
    },
  ];
}
