import { IpoItem } from '../../src/types/index.ts';

export function getSeedIpos(nowIso: string): IpoItem[] {
  return [
    // ----------------------------------------------------
    // MAINBOARD IPOS
    // ----------------------------------------------------
    {
      id: 'ipo-swiggy-fin',
      companyName: 'Bharat SemiCon Technologies Ltd',
      ipoType: 'MAINBOARD',
      openDate: '2026-03-12',
      closeDate: '2026-03-16',
      listingDate: '2026-03-21',
      priceBandMin: 450,
      priceBandMax: 475,
      lotSize: 31,
      minInvestment: 14725,
      issueSizeCr: 3200,
      freshIssueCr: 2400,
      ofsCr: 800,
      faceValue: 5,
      status: 'UPCOMING',
      subscriptions: [
        { category: 'QIB', sharesOffered: 15000000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 11000000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 26000000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 52000000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-1',
        ipoId: 'ipo-swiggy-fin',
        gmpValue: 145,
        previousGmp: 120,
        trend: 'UP',
        changeAmount: 25,
        estimatedListingPrice: 620,
        estimatedPremiumPercent: 30.5,
        observedAt: nowIso,
        source: 'Grey Market Brokerage Indicative Desk',
        sourceConfidence: 85,
      },
      gmpHistory: [
        {
          id: 'gmp-1-h1',
          ipoId: 'ipo-swiggy-fin',
          gmpValue: 95,
          trend: 'FLAT',
          changeAmount: 0,
          estimatedListingPrice: 570,
          estimatedPremiumPercent: 20.0,
          observedAt: '2026-03-05T10:00:00.000Z',
          source: 'Grey Market Brokerage Indicative Desk',
          sourceConfidence: 80,
        },
        {
          id: 'gmp-1-h2',
          ipoId: 'ipo-swiggy-fin',
          gmpValue: 120,
          previousGmp: 95,
          trend: 'UP',
          changeAmount: 25,
          estimatedListingPrice: 595,
          estimatedPremiumPercent: 25.2,
          observedAt: '2026-03-07T10:00:00.000Z',
          source: 'Grey Market Brokerage Indicative Desk',
          sourceConfidence: 82,
        },
        {
          id: 'gmp-1-h3',
          ipoId: 'ipo-swiggy-fin',
          gmpValue: 145,
          previousGmp: 120,
          trend: 'UP',
          changeAmount: 25,
          estimatedListingPrice: 620,
          estimatedPremiumPercent: 30.5,
          observedAt: nowIso,
          source: 'Grey Market Brokerage Indicative Desk',
          sourceConfidence: 85,
        },
      ],
      scores: {
        demandScore: 84,
        gmpSupportScore: {
          score: 85,
          category: 'Strong Positive Support',
          summary: 'Indicative GMP shows steady upward momentum (+₹50 over 4 days) pointing to solid unofficial listing interest.',
        },
        overallIpoScore: {
          total: 82,
          business: 87,
          financials: 79,
          valuation: 74,
          subscription: 78,
          gmpSupport: 85,
          marketSector: 89,
          riskLevel: 'Medium',
        },
      },
      quality: {
        source: 'SEBI DRHP / RHP Public Filing',
        sourceType: 'exchange_filing',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 96,
        status: 'verified',
      },
    },
    {
      id: 'ipo-solar-infra',
      companyName: 'Nava Solar EPC Limited',
      ipoType: 'MAINBOARD',
      openDate: '2026-03-06',
      closeDate: '2026-03-10',
      listingDate: '2026-03-15',
      priceBandMin: 280,
      priceBandMax: 295,
      lotSize: 50,
      minInvestment: 14750,
      issueSizeCr: 1450,
      freshIssueCr: 1100,
      ofsCr: 350,
      faceValue: 10,
      status: 'OPEN',
      subscriptions: [
        { category: 'QIB', sharesOffered: 9800000, sharesBid: 34300000, timesSubscribed: 3.50, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 7350000, sharesBid: 58800000, timesSubscribed: 8.00, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 17150000, sharesBid: 71200000, timesSubscribed: 4.15, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 34300000, sharesBid: 164300000, timesSubscribed: 4.79, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-2',
        ipoId: 'ipo-solar-infra',
        gmpValue: 72,
        previousGmp: 68,
        trend: 'UP',
        changeAmount: 4,
        estimatedListingPrice: 367,
        estimatedPremiumPercent: 24.4,
        observedAt: nowIso,
        source: 'Grey Market Brokerage Indicative Desk',
        sourceConfidence: 85,
      },
      gmpHistory: [
        {
          id: 'gmp-2-h1',
          ipoId: 'ipo-solar-infra',
          gmpValue: 55,
          trend: 'FLAT',
          changeAmount: 0,
          estimatedListingPrice: 350,
          estimatedPremiumPercent: 18.6,
          observedAt: '2026-03-04T12:00:00.000Z',
          source: 'Grey Market Brokerage Indicative Desk',
          sourceConfidence: 82,
        },
        {
          id: 'gmp-2-h2',
          ipoId: 'ipo-solar-infra',
          gmpValue: 68,
          previousGmp: 55,
          trend: 'UP',
          changeAmount: 13,
          estimatedListingPrice: 363,
          estimatedPremiumPercent: 23.0,
          observedAt: '2026-03-07T14:00:00.000Z',
          source: 'Grey Market Brokerage Indicative Desk',
          sourceConfidence: 84,
        },
        {
          id: 'gmp-2-h3',
          ipoId: 'ipo-solar-infra',
          gmpValue: 72,
          previousGmp: 68,
          trend: 'UP',
          changeAmount: 4,
          estimatedListingPrice: 367,
          estimatedPremiumPercent: 24.4,
          observedAt: nowIso,
          source: 'Grey Market Brokerage Indicative Desk',
          sourceConfidence: 85,
        },
      ],
      scores: {
        demandScore: 82,
        gmpSupportScore: {
          score: 79,
          category: 'Positive Support',
          summary: 'Consistent 24% grey market premium backed by healthy Day-2 NII and QIB subscription rates.',
        },
        overallIpoScore: {
          total: 79,
          business: 80,
          financials: 75,
          valuation: 74,
          subscription: 84,
          gmpSupport: 79,
          marketSector: 82,
          riskLevel: 'Medium',
        },
      },
      quality: {
        source: 'NSE/BSE Consolidated Bidding Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 99,
        status: 'verified',
      },
    },
    {
      id: 'ipo-hyundai-comp',
      companyName: 'Hyundai Auto Components India Ltd',
      ipoType: 'MAINBOARD',
      openDate: '2026-03-18',
      closeDate: '2026-03-22',
      listingDate: '2026-03-27',
      priceBandMin: 620,
      priceBandMax: 650,
      lotSize: 23,
      minInvestment: 14950,
      issueSizeCr: 8500,
      freshIssueCr: 3500,
      ofsCr: 5000,
      faceValue: 10,
      status: 'UPCOMING',
      subscriptions: [
        { category: 'QIB', sharesOffered: 45000000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 33750000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 78750000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 157500000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-3',
        ipoId: 'ipo-hyundai-comp',
        gmpValue: 125,
        previousGmp: 110,
        trend: 'UP',
        changeAmount: 15,
        estimatedListingPrice: 775,
        estimatedPremiumPercent: 19.2,
        observedAt: nowIso,
        source: 'Institutional IPO Indicative Quotes',
        sourceConfidence: 88,
      },
      gmpHistory: [
        {
          id: 'gmp-3-h1',
          ipoId: 'ipo-hyundai-comp',
          gmpValue: 110,
          trend: 'FLAT',
          changeAmount: 0,
          estimatedListingPrice: 760,
          estimatedPremiumPercent: 16.9,
          observedAt: '2026-03-05T09:00:00.000Z',
          source: 'Institutional IPO Indicative Quotes',
          sourceConfidence: 86,
        },
        {
          id: 'gmp-3-h2',
          ipoId: 'ipo-hyundai-comp',
          gmpValue: 125,
          previousGmp: 110,
          trend: 'UP',
          changeAmount: 15,
          estimatedListingPrice: 775,
          estimatedPremiumPercent: 19.2,
          observedAt: nowIso,
          source: 'Institutional IPO Indicative Quotes',
          sourceConfidence: 88,
        },
      ],
      scores: {
        demandScore: 86,
        gmpSupportScore: {
          score: 82,
          category: 'Positive Support',
          summary: 'Premier multinational auto Tier-1 vendor with extensive export linkages and strong OEM relationships.',
        },
        overallIpoScore: {
          total: 85,
          business: 90,
          financials: 85,
          valuation: 76,
          subscription: 80,
          gmpSupport: 82,
          marketSector: 88,
          riskLevel: 'Low',
        },
      },
      quality: {
        source: 'SEBI DRHP Red Herring Filing',
        sourceType: 'exchange_filing',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 97,
        status: 'verified',
      },
    },
    {
      id: 'ipo-hexaware-tech',
      companyName: 'Hexaware Digital Technologies Ltd',
      ipoType: 'MAINBOARD',
      openDate: '2026-03-24',
      closeDate: '2026-03-27',
      listingDate: '2026-04-02',
      priceBandMin: 510,
      priceBandMax: 540,
      lotSize: 27,
      minInvestment: 14580,
      issueSizeCr: 4200,
      freshIssueCr: 2100,
      ofsCr: 2100,
      faceValue: 2,
      status: 'UPCOMING',
      subscriptions: [
        { category: 'QIB', sharesOffered: 26000000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 19500000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 45500000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 91000000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-4',
        ipoId: 'ipo-hexaware-tech',
        gmpValue: 120,
        previousGmp: 105,
        trend: 'UP',
        changeAmount: 15,
        estimatedListingPrice: 660,
        estimatedPremiumPercent: 22.2,
        observedAt: nowIso,
        source: 'Grey Market Brokerage Indicative Desk',
        sourceConfidence: 83,
      },
      gmpHistory: [
        {
          id: 'gmp-4-h1',
          ipoId: 'ipo-hexaware-tech',
          gmpValue: 105,
          trend: 'FLAT',
          changeAmount: 0,
          estimatedListingPrice: 645,
          estimatedPremiumPercent: 19.4,
          observedAt: '2026-03-06T10:00:00.000Z',
          source: 'Grey Market Brokerage Indicative Desk',
          sourceConfidence: 81,
        },
        {
          id: 'gmp-4-h2',
          ipoId: 'ipo-hexaware-tech',
          gmpValue: 120,
          previousGmp: 105,
          trend: 'UP',
          changeAmount: 15,
          estimatedListingPrice: 660,
          estimatedPremiumPercent: 22.2,
          observedAt: nowIso,
          source: 'Grey Market Brokerage Indicative Desk',
          sourceConfidence: 83,
        },
      ],
      scores: {
        demandScore: 81,
        gmpSupportScore: {
          score: 80,
          category: 'Positive Support',
          summary: 'Mid-tier IT enterprise software services play with proven AI and automation practice scale.',
        },
        overallIpoScore: {
          total: 80,
          business: 82,
          financials: 83,
          valuation: 75,
          subscription: 77,
          gmpSupport: 80,
          marketSector: 79,
          riskLevel: 'Medium',
        },
      },
      quality: {
        source: 'SEBI Approved DRHP Listing Notice',
        sourceType: 'exchange_filing',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 96,
        status: 'verified',
      },
    },
    {
      id: 'ipo-afcons-infra',
      companyName: 'Afcons Infrastructure Megastructures Ltd',
      ipoType: 'MAINBOARD',
      openDate: '2026-03-08',
      closeDate: '2026-03-12',
      listingDate: '2026-03-18',
      priceBandMin: 440,
      priceBandMax: 463,
      lotSize: 32,
      minInvestment: 14816,
      issueSizeCr: 5430,
      freshIssueCr: 1250,
      ofsCr: 4180,
      faceValue: 10,
      status: 'OPEN',
      subscriptions: [
        { category: 'QIB', sharesOffered: 38000000, sharesBid: 98800000, timesSubscribed: 2.60, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 28500000, sharesBid: 142500000, timesSubscribed: 5.00, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 66500000, sharesBid: 212800000, timesSubscribed: 3.20, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 133000000, sharesBid: 454100000, timesSubscribed: 3.41, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-5',
        ipoId: 'ipo-afcons-infra',
        gmpValue: 74,
        previousGmp: 65,
        trend: 'UP',
        changeAmount: 9,
        estimatedListingPrice: 537,
        estimatedPremiumPercent: 16.0,
        observedAt: nowIso,
        source: 'NSE Consolidated IPO Bidding Center',
        sourceConfidence: 87,
      },
      gmpHistory: [
        {
          id: 'gmp-5-h1',
          ipoId: 'ipo-afcons-infra',
          gmpValue: 65,
          trend: 'FLAT',
          changeAmount: 0,
          estimatedListingPrice: 528,
          estimatedPremiumPercent: 14.0,
          observedAt: '2026-03-06T15:00:00.000Z',
          source: 'Grey Market Brokerage Indicative Desk',
          sourceConfidence: 83,
        },
        {
          id: 'gmp-5-h2',
          ipoId: 'ipo-afcons-infra',
          gmpValue: 74,
          previousGmp: 65,
          trend: 'UP',
          changeAmount: 9,
          estimatedListingPrice: 537,
          estimatedPremiumPercent: 16.0,
          observedAt: nowIso,
          source: 'Grey Market Brokerage Indicative Desk',
          sourceConfidence: 87,
        },
      ],
      scores: {
        demandScore: 78,
        gmpSupportScore: {
          score: 76,
          category: 'Positive Support',
          summary: 'Shapoorji Pallonji flagship engineering business; order book exceeds ₹34,000 Cr across marine and highway infrastructure.',
        },
        overallIpoScore: {
          total: 77,
          business: 85,
          financials: 74,
          valuation: 71,
          subscription: 78,
          gmpSupport: 76,
          marketSector: 82,
          riskLevel: 'Medium',
        },
      },
      quality: {
        source: 'NSE/BSE Consolidated Bidding Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 99,
        status: 'verified',
      },
    },
    {
      id: 'ipo-vishal-mega',
      companyName: 'Vishal Mega Mart Retail Limited',
      ipoType: 'MAINBOARD',
      openDate: '2026-03-20',
      closeDate: '2026-03-25',
      listingDate: '2026-03-31',
      priceBandMin: 74,
      priceBandMax: 78,
      lotSize: 190,
      minInvestment: 14820,
      issueSizeCr: 8000,
      freshIssueCr: 0,
      ofsCr: 8000,
      faceValue: 1,
      status: 'UPCOMING',
      subscriptions: [
        { category: 'QIB', sharesOffered: 340000000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 255000000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 595000000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 1190000000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-6',
        ipoId: 'ipo-vishal-mega',
        gmpValue: 21,
        previousGmp: 18,
        trend: 'UP',
        changeAmount: 3,
        estimatedListingPrice: 99,
        estimatedPremiumPercent: 26.9,
        observedAt: nowIso,
        source: 'Grey Market Brokerage Indicative Desk',
        sourceConfidence: 84,
      },
      gmpHistory: [
        {
          id: 'gmp-6-h1',
          ipoId: 'ipo-vishal-mega',
          gmpValue: 18,
          trend: 'FLAT',
          changeAmount: 0,
          estimatedListingPrice: 96,
          estimatedPremiumPercent: 23.1,
          observedAt: '2026-03-05T12:00:00.000Z',
          source: 'Grey Market Brokerage Indicative Desk',
          sourceConfidence: 82,
        },
        {
          id: 'gmp-6-h2',
          ipoId: 'ipo-vishal-mega',
          gmpValue: 21,
          previousGmp: 18,
          trend: 'UP',
          changeAmount: 3,
          estimatedListingPrice: 99,
          estimatedPremiumPercent: 26.9,
          observedAt: nowIso,
          source: 'Grey Market Brokerage Indicative Desk',
          sourceConfidence: 84,
        },
      ],
      scores: {
        demandScore: 85,
        gmpSupportScore: {
          score: 83,
          category: 'Positive Support',
          summary: 'Tier-2 and Tier-3 value retail leader with 600+ hypermarkets; strong comparable dynamics to Trent and DMart.',
        },
        overallIpoScore: {
          total: 82,
          business: 86,
          financials: 82,
          valuation: 78,
          subscription: 81,
          gmpSupport: 83,
          marketSector: 85,
          riskLevel: 'Medium',
        },
      },
      quality: {
        source: 'SEBI Approved DRHP Public Notice',
        sourceType: 'exchange_filing',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 97,
        status: 'verified',
      },
    },
    {
      id: 'ipo-waaree-solar',
      companyName: 'Waaree Energies CleanTech Ltd',
      ipoType: 'MAINBOARD',
      openDate: '2026-03-26',
      closeDate: '2026-03-30',
      listingDate: '2026-04-06',
      priceBandMin: 1427,
      priceBandMax: 1503,
      lotSize: 9,
      minInvestment: 13527,
      issueSizeCr: 4320,
      freshIssueCr: 3600,
      ofsCr: 720,
      faceValue: 10,
      status: 'UPCOMING',
      subscriptions: [
        { category: 'QIB', sharesOffered: 9600000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 7200000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 16800000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 33600000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-7',
        ipoId: 'ipo-waaree-solar',
        gmpValue: 710,
        previousGmp: 650,
        trend: 'UP',
        changeAmount: 60,
        estimatedListingPrice: 2213,
        estimatedPremiumPercent: 47.2,
        observedAt: nowIso,
        source: 'Specialty CleanTech Syndicate Desk',
        sourceConfidence: 91,
      },
      gmpHistory: [
        {
          id: 'gmp-7-h1',
          ipoId: 'ipo-waaree-solar',
          gmpValue: 580,
          trend: 'UP',
          changeAmount: 80,
          estimatedListingPrice: 2083,
          estimatedPremiumPercent: 38.6,
          observedAt: '2026-03-04T10:00:00.000Z',
          source: 'Specialty CleanTech Syndicate Desk',
          sourceConfidence: 89,
        },
        {
          id: 'gmp-7-h2',
          ipoId: 'ipo-waaree-solar',
          gmpValue: 650,
          previousGmp: 580,
          trend: 'UP',
          changeAmount: 70,
          estimatedListingPrice: 2153,
          estimatedPremiumPercent: 43.2,
          observedAt: '2026-03-07T12:00:00.000Z',
          source: 'Specialty CleanTech Syndicate Desk',
          sourceConfidence: 90,
        },
        {
          id: 'gmp-7-h3',
          ipoId: 'ipo-waaree-solar',
          gmpValue: 710,
          previousGmp: 650,
          trend: 'UP',
          changeAmount: 60,
          estimatedListingPrice: 2213,
          estimatedPremiumPercent: 47.2,
          observedAt: nowIso,
          source: 'Specialty CleanTech Syndicate Desk',
          sourceConfidence: 91,
        },
      ],
      scores: {
        demandScore: 94,
        gmpSupportScore: {
          score: 95,
          category: 'Strong Positive Support',
          summary: 'India’s largest solar PV module manufacturer with 12 GW capacity; extraordinary grey market premium backing (+47%).',
        },
        overallIpoScore: {
          total: 89,
          business: 92,
          financials: 88,
          valuation: 79,
          subscription: 92,
          gmpSupport: 95,
          marketSector: 94,
          riskLevel: 'Medium',
        },
      },
      quality: {
        source: 'SEBI Approved Red Herring Prospectus',
        sourceType: 'exchange_filing',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 99,
        status: 'verified',
      },
    },
    {
      id: 'ipo-swiggy-consumer',
      companyName: 'Swiggy Consumer Tech Limited',
      ipoType: 'MAINBOARD',
      openDate: '2026-03-31',
      closeDate: '2026-04-03',
      listingDate: '2026-04-09',
      priceBandMin: 370,
      priceBandMax: 390,
      lotSize: 38,
      minInvestment: 14820,
      issueSizeCr: 11300,
      freshIssueCr: 4500,
      ofsCr: 6800,
      faceValue: 1,
      status: 'UPCOMING',
      subscriptions: [
        { category: 'QIB', sharesOffered: 96000000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 72000000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 168000000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 336000000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-8',
        ipoId: 'ipo-swiggy-consumer',
        gmpValue: 75,
        previousGmp: 68,
        trend: 'UP',
        changeAmount: 7,
        estimatedListingPrice: 465,
        estimatedPremiumPercent: 19.2,
        observedAt: nowIso,
        source: 'Consumer Tech Syndicate Indicative Desk',
        sourceConfidence: 86,
      },
      gmpHistory: [
        {
          id: 'gmp-8-h1',
          ipoId: 'ipo-swiggy-consumer',
          gmpValue: 68,
          trend: 'FLAT',
          changeAmount: 0,
          estimatedListingPrice: 458,
          estimatedPremiumPercent: 17.4,
          observedAt: '2026-03-06T11:00:00.000Z',
          source: 'Consumer Tech Syndicate Indicative Desk',
          sourceConfidence: 84,
        },
        {
          id: 'gmp-8-h2',
          ipoId: 'ipo-swiggy-consumer',
          gmpValue: 75,
          previousGmp: 68,
          trend: 'UP',
          changeAmount: 7,
          estimatedListingPrice: 465,
          estimatedPremiumPercent: 19.2,
          observedAt: nowIso,
          source: 'Consumer Tech Syndicate Indicative Desk',
          sourceConfidence: 86,
        },
      ],
      scores: {
        demandScore: 83,
        gmpSupportScore: {
          score: 81,
          category: 'Positive Support',
          summary: 'Duopoly position in quick commerce and food delivery with Instamart dark stores expanding GOV over 80% YoY.',
        },
        overallIpoScore: {
          total: 80,
          business: 89,
          financials: 71,
          valuation: 72,
          subscription: 83,
          gmpSupport: 81,
          marketSector: 86,
          riskLevel: 'Medium',
        },
      },
      quality: {
        source: 'SEBI Approved RHP Disclosure',
        sourceType: 'exchange_filing',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 97,
        status: 'verified',
      },
    },
    {
      id: 'ipo-acme-solar',
      companyName: 'ACME Solar Renewable Holdings Ltd',
      ipoType: 'MAINBOARD',
      openDate: '2026-03-05',
      closeDate: '2026-03-09',
      listingDate: '2026-03-14',
      priceBandMin: 275,
      priceBandMax: 289,
      lotSize: 51,
      minInvestment: 14739,
      issueSizeCr: 2900,
      freshIssueCr: 2395,
      ofsCr: 505,
      faceValue: 2,
      status: 'OPEN',
      subscriptions: [
        { category: 'QIB', sharesOffered: 29000000, sharesBid: 92800000, timesSubscribed: 3.20, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 21750000, sharesBid: 110925000, timesSubscribed: 5.10, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 50750000, sharesBid: 167475000, timesSubscribed: 3.30, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 101500000, sharesBid: 371200000, timesSubscribed: 3.66, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-9',
        ipoId: 'ipo-acme-solar',
        gmpValue: 38,
        previousGmp: 34,
        trend: 'UP',
        changeAmount: 4,
        estimatedListingPrice: 327,
        estimatedPremiumPercent: 13.1,
        observedAt: nowIso,
        source: 'Green Energy Desk Quotes',
        sourceConfidence: 84,
      },
      gmpHistory: [
        {
          id: 'gmp-9-h1',
          ipoId: 'ipo-acme-solar',
          gmpValue: 34,
          trend: 'FLAT',
          changeAmount: 0,
          estimatedListingPrice: 323,
          estimatedPremiumPercent: 11.8,
          observedAt: '2026-03-04T12:00:00.000Z',
          source: 'Green Energy Desk Quotes',
          sourceConfidence: 82,
        },
        {
          id: 'gmp-9-h2',
          ipoId: 'ipo-acme-solar',
          gmpValue: 38,
          previousGmp: 34,
          trend: 'UP',
          changeAmount: 4,
          estimatedListingPrice: 327,
          estimatedPremiumPercent: 13.1,
          observedAt: nowIso,
          source: 'Green Energy Desk Quotes',
          sourceConfidence: 84,
        },
      ],
      scores: {
        demandScore: 76,
        gmpSupportScore: {
          score: 74,
          category: 'Positive Support',
          summary: 'Large-scale operational solar and green hydrogen power producer with SECI long-term power purchase agreements.',
        },
        overallIpoScore: {
          total: 76,
          business: 82,
          financials: 73,
          valuation: 72,
          subscription: 76,
          gmpSupport: 74,
          marketSector: 81,
          riskLevel: 'Medium',
        },
      },
      quality: {
        source: 'NSE/BSE Bidding Portal Live',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 99,
        status: 'verified',
      },
    },
    {
      id: 'ipo-niva-bupa',
      companyName: 'Niva Bupa Health Insurance Co',
      ipoType: 'MAINBOARD',
      openDate: '2026-03-23',
      closeDate: '2026-03-26',
      listingDate: '2026-04-01',
      priceBandMin: 70,
      priceBandMax: 74,
      lotSize: 200,
      minInvestment: 14800,
      issueSizeCr: 2200,
      freshIssueCr: 800,
      ofsCr: 1400,
      faceValue: 10,
      status: 'UPCOMING',
      subscriptions: [
        { category: 'QIB', sharesOffered: 88000000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 66000000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 154000000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 308000000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-10',
        ipoId: 'ipo-niva-bupa',
        gmpValue: 12,
        previousGmp: 10,
        trend: 'UP',
        changeAmount: 2,
        estimatedListingPrice: 86,
        estimatedPremiumPercent: 16.2,
        observedAt: nowIso,
        source: 'BFSI Syndicate Desk',
        sourceConfidence: 85,
      },
      gmpHistory: [
        {
          id: 'gmp-10-h1',
          ipoId: 'ipo-niva-bupa',
          gmpValue: 10,
          trend: 'FLAT',
          changeAmount: 0,
          estimatedListingPrice: 84,
          estimatedPremiumPercent: 13.5,
          observedAt: '2026-03-05T14:00:00.000Z',
          source: 'BFSI Syndicate Desk',
          sourceConfidence: 83,
        },
        {
          id: 'gmp-10-h2',
          ipoId: 'ipo-niva-bupa',
          gmpValue: 12,
          previousGmp: 10,
          trend: 'UP',
          changeAmount: 2,
          estimatedListingPrice: 86,
          estimatedPremiumPercent: 16.2,
          observedAt: nowIso,
          source: 'BFSI Syndicate Desk',
          sourceConfidence: 85,
        },
      ],
      scores: {
        demandScore: 77,
        gmpSupportScore: {
          score: 77,
          category: 'Positive Support',
          summary: 'Pure-play standalone health insurer with strong direct distribution and low claims processing turnaround.',
        },
        overallIpoScore: {
          total: 78,
          business: 83,
          financials: 77,
          valuation: 73,
          subscription: 78,
          gmpSupport: 77,
          marketSector: 82,
          riskLevel: 'Medium',
        },
      },
      quality: {
        source: 'IRDAI & SEBI Registered Filing',
        sourceType: 'exchange_filing',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 97,
        status: 'verified',
      },
    },

    // ----------------------------------------------------
    // SME IPOS (NSE EMERGE & BSE SME)
    // ----------------------------------------------------
    {
      id: 'ipo-sme-apex-aerospace',
      companyName: 'Apex Precision Aerospace SME Ltd',
      ipoType: 'SME',
      openDate: '2026-03-09',
      closeDate: '2026-03-11',
      listingDate: '2026-03-17',
      priceBandMin: 110,
      priceBandMax: 115,
      lotSize: 1200,
      minInvestment: 138000,
      issueSizeCr: 48.5,
      freshIssueCr: 48.5,
      ofsCr: 0,
      faceValue: 10,
      status: 'OPEN',
      subscriptions: [
        { category: 'QIB', sharesOffered: 800000, sharesBid: 9600000, timesSubscribed: 12.0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 600000, sharesBid: 21600000, timesSubscribed: 36.0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 1400000, sharesBid: 25200000, timesSubscribed: 18.0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 2800000, sharesBid: 56400000, timesSubscribed: 20.14, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-sme-1',
        ipoId: 'ipo-sme-apex-aerospace',
        gmpValue: 65,
        previousGmp: 50,
        trend: 'UP',
        changeAmount: 15,
        estimatedListingPrice: 180,
        estimatedPremiumPercent: 56.5,
        observedAt: nowIso,
        source: 'SME Merchant Banker Desk Tracking',
        sourceConfidence: 82,
      },
      gmpHistory: [
        {
          id: 'gmp-sme-h1',
          ipoId: 'ipo-sme-apex-aerospace',
          gmpValue: 35,
          trend: 'FLAT',
          changeAmount: 0,
          estimatedListingPrice: 150,
          estimatedPremiumPercent: 30.4,
          observedAt: '2026-03-06T10:00:00.000Z',
          source: 'SME Merchant Banker Desk Tracking',
          sourceConfidence: 78,
        },
        {
          id: 'gmp-sme-h2',
          ipoId: 'ipo-sme-apex-aerospace',
          gmpValue: 50,
          previousGmp: 35,
          trend: 'UP',
          changeAmount: 15,
          estimatedListingPrice: 165,
          estimatedPremiumPercent: 43.4,
          observedAt: '2026-03-08T11:00:00.000Z',
          source: 'SME Merchant Banker Desk Tracking',
          sourceConfidence: 80,
        },
        {
          id: 'gmp-sme-h3',
          ipoId: 'ipo-sme-apex-aerospace',
          gmpValue: 65,
          previousGmp: 50,
          trend: 'UP',
          changeAmount: 15,
          estimatedListingPrice: 180,
          estimatedPremiumPercent: 56.5,
          observedAt: nowIso,
          source: 'SME Merchant Banker Desk Tracking',
          sourceConfidence: 82,
        },
      ],
      scores: {
        demandScore: 89,
        gmpSupportScore: {
          score: 92,
          category: 'Strong Positive Support',
          summary: 'High SME demand with 20x overall Day-1 bid coverage and 56% indicative premium in aerospace precision engineering.',
        },
        overallIpoScore: {
          total: 83,
          business: 84,
          financials: 79,
          valuation: 75,
          subscription: 94,
          gmpSupport: 92,
          marketSector: 85,
          riskLevel: 'High',
        },
      },
      quality: {
        source: 'BSE SME Platform Live Bidding',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 98,
        status: 'verified',
      },
    },
    {
      id: 'ipo-sme-suntech-ev',
      companyName: 'SunTech EV Mobility SME Ltd',
      ipoType: 'SME',
      openDate: '2026-03-08',
      closeDate: '2026-03-11',
      listingDate: '2026-03-16',
      priceBandMin: 85,
      priceBandMax: 90,
      lotSize: 1600,
      minInvestment: 144000,
      issueSizeCr: 34.2,
      freshIssueCr: 34.2,
      ofsCr: 0,
      faceValue: 10,
      status: 'OPEN',
      subscriptions: [
        { category: 'QIB', sharesOffered: 760000, sharesBid: 6840000, timesSubscribed: 9.0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 570000, sharesBid: 14820000, timesSubscribed: 26.0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 1330000, sharesBid: 18620000, timesSubscribed: 14.0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 2660000, sharesBid: 40280000, timesSubscribed: 15.14, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-sme-2',
        ipoId: 'ipo-sme-suntech-ev',
        gmpValue: 38,
        previousGmp: 28,
        trend: 'UP',
        changeAmount: 10,
        estimatedListingPrice: 128,
        estimatedPremiumPercent: 42.2,
        observedAt: nowIso,
        source: 'NSE Emerge Brokerage Desk',
        sourceConfidence: 81,
      },
      gmpHistory: [
        {
          id: 'gmp-sme-2-h1',
          ipoId: 'ipo-sme-suntech-ev',
          gmpValue: 28,
          trend: 'FLAT',
          changeAmount: 0,
          estimatedListingPrice: 118,
          estimatedPremiumPercent: 31.1,
          observedAt: '2026-03-06T12:00:00.000Z',
          source: 'NSE Emerge Brokerage Desk',
          sourceConfidence: 79,
        },
        {
          id: 'gmp-sme-2-h2',
          ipoId: 'ipo-sme-suntech-ev',
          gmpValue: 38,
          previousGmp: 28,
          trend: 'UP',
          changeAmount: 10,
          estimatedListingPrice: 128,
          estimatedPremiumPercent: 42.2,
          observedAt: nowIso,
          source: 'NSE Emerge Brokerage Desk',
          sourceConfidence: 81,
        },
      ],
      scores: {
        demandScore: 86,
        gmpSupportScore: {
          score: 87,
          category: 'Strong Positive Support',
          summary: 'Supplies lithium-ion battery management systems (BMS) for commercial 3-wheelers with fast top-line growth.',
        },
        overallIpoScore: {
          total: 81,
          business: 82,
          financials: 77,
          valuation: 76,
          subscription: 88,
          gmpSupport: 87,
          marketSector: 84,
          riskLevel: 'High',
        },
      },
      quality: {
        source: 'NSE Emerge Live Bidding Console',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 99,
        status: 'verified',
      },
    },
    {
      id: 'ipo-sme-quantum-pharma',
      companyName: 'Quantum BioPharma SME Ltd',
      ipoType: 'SME',
      openDate: '2026-03-16',
      closeDate: '2026-03-19',
      listingDate: '2026-03-25',
      priceBandMin: 140,
      priceBandMax: 148,
      lotSize: 1000,
      minInvestment: 148000,
      issueSizeCr: 28.5,
      freshIssueCr: 28.5,
      ofsCr: 0,
      faceValue: 10,
      status: 'UPCOMING',
      subscriptions: [
        { category: 'QIB', sharesOffered: 380000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 285000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 665000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 1330000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-sme-3',
        ipoId: 'ipo-sme-quantum-pharma',
        gmpValue: 56,
        previousGmp: 45,
        trend: 'UP',
        changeAmount: 11,
        estimatedListingPrice: 204,
        estimatedPremiumPercent: 37.8,
        observedAt: nowIso,
        source: 'SME Merchant Banker Desk Tracking',
        sourceConfidence: 80,
      },
      gmpHistory: [
        {
          id: 'gmp-sme-3-h1',
          ipoId: 'ipo-sme-quantum-pharma',
          gmpValue: 45,
          trend: 'FLAT',
          changeAmount: 0,
          estimatedListingPrice: 193,
          estimatedPremiumPercent: 30.4,
          observedAt: '2026-03-06T14:00:00.000Z',
          source: 'SME Merchant Banker Desk Tracking',
          sourceConfidence: 78,
        },
        {
          id: 'gmp-sme-3-h2',
          ipoId: 'ipo-sme-quantum-pharma',
          gmpValue: 56,
          previousGmp: 45,
          trend: 'UP',
          changeAmount: 11,
          estimatedListingPrice: 204,
          estimatedPremiumPercent: 37.8,
          observedAt: nowIso,
          source: 'SME Merchant Banker Desk Tracking',
          sourceConfidence: 80,
        },
      ],
      scores: {
        demandScore: 82,
        gmpSupportScore: {
          score: 84,
          category: 'Positive Support',
          summary: 'Specialty API formulation with export approvals in LATAM and Southeast Asia; strong RoCE of 28%.',
        },
        overallIpoScore: {
          total: 80,
          business: 84,
          financials: 81,
          valuation: 73,
          subscription: 79,
          gmpSupport: 84,
          marketSector: 81,
          riskLevel: 'High',
        },
      },
      quality: {
        source: 'BSE SME Registered Prospectus',
        sourceType: 'exchange_filing',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 96,
        status: 'verified',
      },
    },
    {
      id: 'ipo-sme-greengrid',
      companyName: 'GreenGrid Power Controls SME Ltd',
      ipoType: 'SME',
      openDate: '2026-03-17',
      closeDate: '2026-03-20',
      listingDate: '2026-03-26',
      priceBandMin: 120,
      priceBandMax: 126,
      lotSize: 1000,
      minInvestment: 126000,
      issueSizeCr: 41.2,
      freshIssueCr: 35.0,
      ofsCr: 6.2,
      faceValue: 10,
      status: 'UPCOMING',
      subscriptions: [
        { category: 'QIB', sharesOffered: 650000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 490000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 1140000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 2280000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-sme-4',
        ipoId: 'ipo-sme-greengrid',
        gmpValue: 58,
        previousGmp: 48,
        trend: 'UP',
        changeAmount: 10,
        estimatedListingPrice: 184,
        estimatedPremiumPercent: 46.0,
        observedAt: nowIso,
        source: 'NSE Emerge Brokerage Desk',
        sourceConfidence: 82,
      },
      gmpHistory: [
        {
          id: 'gmp-sme-4-h1',
          ipoId: 'ipo-sme-greengrid',
          gmpValue: 48,
          trend: 'FLAT',
          changeAmount: 0,
          estimatedListingPrice: 174,
          estimatedPremiumPercent: 38.0,
          observedAt: '2026-03-05T11:00:00.000Z',
          source: 'NSE Emerge Brokerage Desk',
          sourceConfidence: 80,
        },
        {
          id: 'gmp-sme-4-h2',
          ipoId: 'ipo-sme-greengrid',
          gmpValue: 58,
          previousGmp: 48,
          trend: 'UP',
          changeAmount: 10,
          estimatedListingPrice: 184,
          estimatedPremiumPercent: 46.0,
          observedAt: nowIso,
          source: 'NSE Emerge Brokerage Desk',
          sourceConfidence: 82,
        },
      ],
      scores: {
        demandScore: 84,
        gmpSupportScore: {
          score: 86,
          category: 'Strong Positive Support',
          summary: 'Smart grid monitoring systems and automated switchgear benefiting from national RDSS distribution schemes.',
        },
        overallIpoScore: {
          total: 82,
          business: 83,
          financials: 80,
          valuation: 75,
          subscription: 82,
          gmpSupport: 86,
          marketSector: 85,
          riskLevel: 'High',
        },
      },
      quality: {
        source: 'NSE Emerge DRHP Filing',
        sourceType: 'exchange_filing',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 96,
        status: 'verified',
      },
    },
    {
      id: 'ipo-sme-aeromech',
      companyName: 'AeroMech Defence Systems SME Ltd',
      ipoType: 'SME',
      openDate: '2026-03-07',
      closeDate: '2026-03-10',
      listingDate: '2026-03-15',
      priceBandMin: 185,
      priceBandMax: 195,
      lotSize: 600,
      minInvestment: 117000,
      issueSizeCr: 36.8,
      freshIssueCr: 36.8,
      ofsCr: 0,
      faceValue: 10,
      status: 'OPEN',
      subscriptions: [
        { category: 'QIB', sharesOffered: 375000, sharesBid: 6750000, timesSubscribed: 18.0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 285000, sharesBid: 14250000, timesSubscribed: 50.0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 665000, sharesBid: 17290000, timesSubscribed: 26.0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 1325000, sharesBid: 38290000, timesSubscribed: 28.89, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-sme-5',
        ipoId: 'ipo-sme-aeromech',
        gmpValue: 122,
        previousGmp: 100,
        trend: 'UP',
        changeAmount: 22,
        estimatedListingPrice: 317,
        estimatedPremiumPercent: 62.5,
        observedAt: nowIso,
        source: 'BSE SME Syndicate Quotes',
        sourceConfidence: 86,
      },
      gmpHistory: [
        {
          id: 'gmp-sme-5-h1',
          ipoId: 'ipo-sme-aeromech',
          gmpValue: 80,
          trend: 'FLAT',
          changeAmount: 0,
          estimatedListingPrice: 275,
          estimatedPremiumPercent: 41.0,
          observedAt: '2026-03-05T12:00:00.000Z',
          source: 'BSE SME Syndicate Quotes',
          sourceConfidence: 82,
        },
        {
          id: 'gmp-sme-5-h2',
          ipoId: 'ipo-sme-aeromech',
          gmpValue: 100,
          previousGmp: 80,
          trend: 'UP',
          changeAmount: 20,
          estimatedListingPrice: 295,
          estimatedPremiumPercent: 51.2,
          observedAt: '2026-03-07T14:00:00.000Z',
          source: 'BSE SME Syndicate Quotes',
          sourceConfidence: 84,
        },
        {
          id: 'gmp-sme-5-h3',
          ipoId: 'ipo-sme-aeromech',
          gmpValue: 122,
          previousGmp: 100,
          trend: 'UP',
          changeAmount: 22,
          estimatedListingPrice: 317,
          estimatedPremiumPercent: 62.5,
          observedAt: nowIso,
          source: 'BSE SME Syndicate Quotes',
          sourceConfidence: 86,
        },
      ],
      scores: {
        demandScore: 92,
        gmpSupportScore: {
          score: 96,
          category: 'Strong Positive Support',
          summary: 'Extremely high subscription demand with 29x total coverage; precision aerospace components supplier to DRDO and ISRO.',
        },
        overallIpoScore: {
          total: 86,
          business: 88,
          financials: 82,
          valuation: 75,
          subscription: 96,
          gmpSupport: 96,
          marketSector: 89,
          riskLevel: 'High',
        },
      },
      quality: {
        source: 'BSE SME Consolidated Bidding Terminal',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 99,
        status: 'verified',
      },
    },
    {
      id: 'ipo-sme-zenagro',
      companyName: 'ZenAgro Chemical Organics SME Ltd',
      ipoType: 'SME',
      openDate: '2026-03-19',
      closeDate: '2026-03-24',
      listingDate: '2026-03-30',
      priceBandMin: 72,
      priceBandMax: 76,
      lotSize: 1600,
      minInvestment: 121600,
      issueSizeCr: 24.5,
      freshIssueCr: 24.5,
      ofsCr: 0,
      faceValue: 10,
      status: 'UPCOMING',
      subscriptions: [
        { category: 'QIB', sharesOffered: 640000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 480000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 1120000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 2240000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-sme-6',
        ipoId: 'ipo-sme-zenagro',
        gmpValue: 22,
        previousGmp: 18,
        trend: 'UP',
        changeAmount: 4,
        estimatedListingPrice: 98,
        estimatedPremiumPercent: 28.9,
        observedAt: nowIso,
        source: 'AgriTech IPO Syndicate Desk',
        sourceConfidence: 80,
      },
      gmpHistory: [
        {
          id: 'gmp-sme-6-h1',
          ipoId: 'ipo-sme-zenagro',
          gmpValue: 18,
          trend: 'FLAT',
          changeAmount: 0,
          estimatedListingPrice: 94,
          estimatedPremiumPercent: 23.6,
          observedAt: '2026-03-06T10:00:00.000Z',
          source: 'AgriTech IPO Syndicate Desk',
          sourceConfidence: 78,
        },
        {
          id: 'gmp-sme-6-h2',
          ipoId: 'ipo-sme-zenagro',
          gmpValue: 22,
          previousGmp: 18,
          trend: 'UP',
          changeAmount: 4,
          estimatedListingPrice: 98,
          estimatedPremiumPercent: 28.9,
          observedAt: nowIso,
          source: 'AgriTech IPO Syndicate Desk',
          sourceConfidence: 80,
        },
      ],
      scores: {
        demandScore: 78,
        gmpSupportScore: {
          score: 80,
          category: 'Positive Support',
          summary: 'Bio-stimulants and certified organic crop protection products with 400+ rural distributor retail points.',
        },
        overallIpoScore: {
          total: 77,
          business: 79,
          financials: 77,
          valuation: 75,
          subscription: 76,
          gmpSupport: 80,
          marketSector: 76,
          riskLevel: 'High',
        },
      },
      quality: {
        source: 'BSE SME Regulatory RHP Filing',
        sourceType: 'exchange_filing',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 96,
        status: 'verified',
      },
    },
    {
      id: 'ipo-sme-finedge',
      companyName: 'FinEdge Payment Technologies SME Ltd',
      ipoType: 'SME',
      openDate: '2026-03-22',
      closeDate: '2026-03-25',
      listingDate: '2026-03-31',
      priceBandMin: 130,
      priceBandMax: 138,
      lotSize: 1000,
      minInvestment: 138000,
      issueSizeCr: 39.0,
      freshIssueCr: 39.0,
      ofsCr: 0,
      faceValue: 10,
      status: 'UPCOMING',
      subscriptions: [
        { category: 'QIB', sharesOffered: 560000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 420000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 980000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 1960000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-sme-7',
        ipoId: 'ipo-sme-finedge',
        gmpValue: 48,
        previousGmp: 40,
        trend: 'UP',
        changeAmount: 8,
        estimatedListingPrice: 186,
        estimatedPremiumPercent: 34.7,
        observedAt: nowIso,
        source: 'Fintech SME Market Desk',
        sourceConfidence: 81,
      },
      gmpHistory: [
        {
          id: 'gmp-sme-7-h1',
          ipoId: 'ipo-sme-finedge',
          gmpValue: 40,
          trend: 'FLAT',
          changeAmount: 0,
          estimatedListingPrice: 178,
          estimatedPremiumPercent: 28.9,
          observedAt: '2026-03-05T13:00:00.000Z',
          source: 'Fintech SME Market Desk',
          sourceConfidence: 79,
        },
        {
          id: 'gmp-sme-7-h2',
          ipoId: 'ipo-sme-finedge',
          gmpValue: 48,
          previousGmp: 40,
          trend: 'UP',
          changeAmount: 8,
          estimatedListingPrice: 186,
          estimatedPremiumPercent: 34.7,
          observedAt: nowIso,
          source: 'Fintech SME Market Desk',
          sourceConfidence: 81,
        },
      ],
      scores: {
        demandScore: 81,
        gmpSupportScore: {
          score: 83,
          category: 'Positive Support',
          summary: 'Proprietary soundbox and biometric micro-ATM POS hardware manufacturer partnering with regional rural banks.',
        },
        overallIpoScore: {
          total: 80,
          business: 82,
          financials: 80,
          valuation: 75,
          subscription: 80,
          gmpSupport: 83,
          marketSector: 81,
          riskLevel: 'High',
        },
      },
      quality: {
        source: 'NSE Emerge Draft Prospectus',
        sourceType: 'exchange_filing',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 96,
        status: 'verified',
      },
    },
    {
      id: 'ipo-sme-logiexpress',
      companyName: 'LogiExpress Cold Chain SME Ltd',
      ipoType: 'SME',
      openDate: '2026-03-08',
      closeDate: '2026-03-12',
      listingDate: '2026-03-18',
      priceBandMin: 98,
      priceBandMax: 104,
      lotSize: 1200,
      minInvestment: 124800,
      issueSizeCr: 31.5,
      freshIssueCr: 31.5,
      ofsCr: 0,
      faceValue: 10,
      status: 'OPEN',
      subscriptions: [
        { category: 'QIB', sharesOffered: 600000, sharesBid: 4200000, timesSubscribed: 7.0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 450000, sharesBid: 9900000, timesSubscribed: 22.0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 1050000, sharesBid: 12600000, timesSubscribed: 12.0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 2100000, sharesBid: 26700000, timesSubscribed: 12.71, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-sme-8',
        ipoId: 'ipo-sme-logiexpress',
        gmpValue: 42,
        previousGmp: 34,
        trend: 'UP',
        changeAmount: 8,
        estimatedListingPrice: 146,
        estimatedPremiumPercent: 40.3,
        observedAt: nowIso,
        source: 'SME Merchant Banker Desk Tracking',
        sourceConfidence: 82,
      },
      gmpHistory: [
        {
          id: 'gmp-sme-8-h1',
          ipoId: 'ipo-sme-logiexpress',
          gmpValue: 34,
          trend: 'FLAT',
          changeAmount: 0,
          estimatedListingPrice: 138,
          estimatedPremiumPercent: 32.6,
          observedAt: '2026-03-06T11:00:00.000Z',
          source: 'SME Merchant Banker Desk Tracking',
          sourceConfidence: 80,
        },
        {
          id: 'gmp-sme-8-h2',
          ipoId: 'ipo-sme-logiexpress',
          gmpValue: 42,
          previousGmp: 34,
          trend: 'UP',
          changeAmount: 8,
          estimatedListingPrice: 146,
          estimatedPremiumPercent: 40.3,
          observedAt: nowIso,
          source: 'SME Merchant Banker Desk Tracking',
          sourceConfidence: 82,
        },
      ],
      scores: {
        demandScore: 84,
        gmpSupportScore: {
          score: 85,
          category: 'Strong Positive Support',
          summary: 'Pharma temperature-controlled fleet operator catering to vaccine and biological exports with long-term contracts.',
        },
        overallIpoScore: {
          total: 81,
          business: 83,
          financials: 78,
          valuation: 75,
          subscription: 85,
          gmpSupport: 85,
          marketSector: 82,
          riskLevel: 'High',
        },
      },
      quality: {
        source: 'BSE SME Bidding Console Live',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 99,
        status: 'verified',
      },
    },
  ];
}
