import { IpoItem } from '../../src/types/index.ts';

export function getSeedIpos(nowIso: string): IpoItem[] {
  return [
    // ====================================================
    // 1. MAINBOARD IPOS (REAL & ACTIVE INDIAN OFFERINGS)
    // ====================================================
    {
      id: 'ipo-waaree-energies',
      symbol: 'WAAREE',
      companyName: 'Waaree Energies Limited',
      ipoType: 'MAINBOARD',
      openDate: '2024-10-21',
      closeDate: '2024-10-23',
      listingDate: '2024-10-28',
      priceBandMin: 1427,
      priceBandMax: 1503,
      lotSize: 9,
      minInvestment: 13527,
      issueSizeCr: 4321.44,
      freshIssueCr: 3600.0,
      ofsCr: 721.44,
      faceValue: 10,
      status: 'OPEN',
      subscriptions: [
        { category: 'QIB', sharesOffered: 5971428, sharesBid: 1245640000, timesSubscribed: 208.63, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 4478571, sharesBid: 279910000, timesSubscribed: 62.50, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 10450000, sharesBid: 112860000, timesSubscribed: 10.80, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 20900000, sharesBid: 1594800000, timesSubscribed: 76.30, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-waaree',
        ipoId: 'ipo-waaree-energies',
        gmpValue: 1475,
        previousGmp: 1380,
        trend: 'UP',
        changeAmount: 95,
        estimatedListingPrice: 2978,
        estimatedPremiumPercent: 98.14,
        observedAt: nowIso,
        source: 'Chittorgarh & Grey Market Indicative Desk',
        sourceConfidence: 94,
      },
      gmpHistory: [
        {
          id: 'gmp-waaree-1',
          ipoId: 'ipo-waaree-energies',
          gmpValue: 1250,
          trend: 'UP',
          changeAmount: 150,
          estimatedListingPrice: 2753,
          estimatedPremiumPercent: 83.17,
          observedAt: '2024-10-18T10:00:00.000Z',
          source: 'Grey Market Indicative Desk',
          sourceConfidence: 90,
        },
        {
          id: 'gmp-waaree-2',
          ipoId: 'ipo-waaree-energies',
          gmpValue: 1380,
          previousGmp: 1250,
          trend: 'UP',
          changeAmount: 130,
          estimatedListingPrice: 2883,
          estimatedPremiumPercent: 91.82,
          observedAt: '2024-10-20T14:00:00.000Z',
          source: 'Grey Market Indicative Desk',
          sourceConfidence: 92,
        },
        {
          id: 'gmp-waaree-3',
          ipoId: 'ipo-waaree-energies',
          gmpValue: 1475,
          previousGmp: 1380,
          trend: 'UP',
          changeAmount: 95,
          estimatedListingPrice: 2978,
          estimatedPremiumPercent: 98.14,
          observedAt: nowIso,
          source: 'Grey Market Indicative Desk',
          sourceConfidence: 94,
        },
      ],
      scores: {
        demandScore: 98,
        gmpSupportScore: {
          score: 99,
          category: 'Strong Positive Support',
          summary: 'Exceptional grey market premium of ~98% driven by dominant 12 GW solar module capacity and 208x QIB demand.',
        },
        overallIpoScore: {
          total: 94,
          business: 96,
          financials: 92,
          valuation: 85,
          subscription: 98,
          gmpSupport: 99,
          marketSector: 95,
          riskLevel: 'Low',
        },
      },
      quality: {
        source: 'SEBI RHP / NSE & BSE Official Filing',
        sourceType: 'exchange_filing',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 99,
        status: 'verified',
      },
    },
    {
      id: 'ipo-hyundai-india',
      symbol: 'HYUNDAI',
      companyName: 'Hyundai Motor India Limited',
      ipoType: 'MAINBOARD',
      openDate: '2024-10-15',
      closeDate: '2024-10-17',
      listingDate: '2024-10-22',
      priceBandMin: 1865,
      priceBandMax: 1960,
      lotSize: 7,
      minInvestment: 13720,
      issueSizeCr: 27870.16,
      freshIssueCr: 0,
      ofsCr: 27870.16,
      faceValue: 10,
      status: 'OPEN',
      subscriptions: [
        { category: 'QIB', sharesOffered: 28249000, sharesBid: 196895000, timesSubscribed: 6.97, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 21186000, sharesBid: 12711000, timesSubscribed: 0.60, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 49435000, sharesBid: 24717000, timesSubscribed: 0.50, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 99742000, sharesBid: 236389000, timesSubscribed: 2.37, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-hyundai',
        ipoId: 'ipo-hyundai-india',
        gmpValue: 45,
        previousGmp: 65,
        trend: 'DOWN',
        changeAmount: -20,
        estimatedListingPrice: 2005,
        estimatedPremiumPercent: 2.3,
        observedAt: nowIso,
        source: 'Grey Market Indicative Desk',
        sourceConfidence: 91,
      },
      gmpHistory: [
        {
          id: 'gmp-h-1',
          ipoId: 'ipo-hyundai-india',
          gmpValue: 110,
          trend: 'UP',
          changeAmount: 0,
          estimatedListingPrice: 2070,
          estimatedPremiumPercent: 5.61,
          observedAt: '2024-10-12T10:00:00.000Z',
          source: 'Grey Market Indicative Desk',
          sourceConfidence: 88,
        },
        {
          id: 'gmp-h-2',
          ipoId: 'ipo-hyundai-india',
          gmpValue: 65,
          previousGmp: 110,
          trend: 'DOWN',
          changeAmount: -45,
          estimatedListingPrice: 2025,
          estimatedPremiumPercent: 3.32,
          observedAt: '2024-10-15T12:00:00.000Z',
          source: 'Grey Market Indicative Desk',
          sourceConfidence: 89,
        },
        {
          id: 'gmp-h-3',
          ipoId: 'ipo-hyundai-india',
          gmpValue: 45,
          previousGmp: 65,
          trend: 'DOWN',
          changeAmount: -20,
          estimatedListingPrice: 2005,
          estimatedPremiumPercent: 2.3,
          observedAt: nowIso,
          source: 'Grey Market Indicative Desk',
          sourceConfidence: 91,
        },
      ],
      scores: {
        demandScore: 72,
        gmpSupportScore: {
          score: 65,
          category: 'Neutral',
          summary: 'India’s largest IPO in history ($3.3B); moderate GMP premium (+2.3%) given mega issue size and pure OFS nature.',
        },
        overallIpoScore: {
          total: 81,
          business: 94,
          financials: 88,
          valuation: 68,
          subscription: 72,
          gmpSupport: 65,
          marketSector: 88,
          riskLevel: 'Medium',
        },
      },
      quality: {
        source: 'SEBI RHP / NSE & BSE Official Filing',
        sourceType: 'exchange_filing',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 99,
        status: 'verified',
      },
    },
    {
      id: 'ipo-bajaj-housing',
      symbol: 'BAJAJHFL',
      companyName: 'Bajaj Housing Finance Limited',
      ipoType: 'MAINBOARD',
      openDate: '2024-09-09',
      closeDate: '2024-09-11',
      listingDate: '2024-09-16',
      priceBandMin: 66,
      priceBandMax: 70,
      lotSize: 214,
      minInvestment: 14980,
      issueSizeCr: 6560.0,
      freshIssueCr: 3560.0,
      ofsCr: 3000.0,
      faceValue: 10,
      status: 'LISTED',
      subscriptions: [
        { category: 'QIB', sharesOffered: 177000000, sharesBid: 39294000000, timesSubscribed: 222.0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 132700000, sharesBid: 5812260000, timesSubscribed: 43.8, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 309700000, sharesBid: 2291780000, timesSubscribed: 7.4, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 619400000, sharesBid: 41747000000, timesSubscribed: 67.4, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-bajaj',
        ipoId: 'ipo-bajaj-housing',
        gmpValue: 80,
        previousGmp: 75,
        trend: 'UP',
        changeAmount: 5,
        estimatedListingPrice: 150,
        estimatedPremiumPercent: 114.28,
        observedAt: nowIso,
        source: 'Actual Listing Day Price (NSE/BSE)',
        sourceConfidence: 100,
      },
      gmpHistory: [],
      scores: {
        demandScore: 99,
        gmpSupportScore: {
          score: 99,
          category: 'Strong Positive Support',
          summary: 'Bumper listing debut: listed at ₹150 (+114.3% listing gain) vs ₹70 issue price with over ₹3.2 lakh crore bids received.',
        },
        overallIpoScore: {
          total: 96,
          business: 98,
          financials: 95,
          valuation: 88,
          subscription: 99,
          gmpSupport: 99,
          marketSector: 96,
          riskLevel: 'Low',
        },
      },
      quality: {
        source: 'National Stock Exchange (NSE) Trade Engine',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
    },
    {
      id: 'ipo-afcons-infra',
      symbol: 'AFCONS',
      companyName: 'Afcons Infrastructure Limited (Shapoorji Pallonji)',
      ipoType: 'MAINBOARD',
      openDate: '2024-10-25',
      closeDate: '2024-10-29',
      listingDate: '2024-11-04',
      priceBandMin: 440,
      priceBandMax: 463,
      lotSize: 32,
      minInvestment: 14816,
      issueSizeCr: 5430.0,
      freshIssueCr: 1250.0,
      ofsCr: 4180.0,
      faceValue: 10,
      status: 'UPCOMING',
      subscriptions: [
        { category: 'QIB', sharesOffered: 5863930, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 4397948, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 10261878, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 20523756, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-afcons',
        ipoId: 'ipo-afcons-infra',
        gmpValue: 85,
        previousGmp: 70,
        trend: 'UP',
        changeAmount: 15,
        estimatedListingPrice: 548,
        estimatedPremiumPercent: 18.36,
        observedAt: nowIso,
        source: 'Grey Market Indicative Desk',
        sourceConfidence: 89,
      },
      gmpHistory: [],
      scores: {
        demandScore: 84,
        gmpSupportScore: {
          score: 82,
          category: 'Positive Support',
          summary: 'Strong ₹34,000+ Cr EPC order book backed by marquee marine, metro, and bridge infrastructure executions.',
        },
        overallIpoScore: {
          total: 83,
          business: 89,
          financials: 82,
          valuation: 78,
          subscription: 80,
          gmpSupport: 82,
          marketSector: 86,
          riskLevel: 'Medium',
        },
      },
      quality: {
        source: 'SEBI Approved RHP Prospectus',
        sourceType: 'exchange_filing',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 98,
        status: 'verified',
      },
    },
    {
      id: 'ipo-northern-arc',
      symbol: 'NORTHARC',
      companyName: 'Northern ARC Capital Limited',
      ipoType: 'MAINBOARD',
      openDate: '2024-09-16',
      closeDate: '2024-09-19',
      listingDate: '2024-09-24',
      priceBandMin: 249,
      priceBandMax: 263,
      lotSize: 57,
      minInvestment: 14991,
      issueSizeCr: 777.0,
      freshIssueCr: 500.0,
      ofsCr: 277.0,
      faceValue: 10,
      status: 'LISTED',
      subscriptions: [
        { category: 'QIB', sharesOffered: 5450000, sharesBid: 728120000, timesSubscribed: 133.6, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 4087500, sharesBid: 582060000, timesSubscribed: 142.4, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 9537500, sharesBid: 296616000, timesSubscribed: 31.1, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 19075000, sharesBid: 2115400000, timesSubscribed: 110.9, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-northern-arc',
        ipoId: 'ipo-northern-arc',
        gmpValue: 88,
        previousGmp: 80,
        trend: 'UP',
        changeAmount: 8,
        estimatedListingPrice: 351,
        estimatedPremiumPercent: 33.46,
        observedAt: nowIso,
        source: 'NSE / BSE Official Listing',
        sourceConfidence: 100,
      },
      gmpHistory: [],
      scores: {
        demandScore: 92,
        gmpSupportScore: {
          score: 90,
          category: 'Strong Positive Support',
          summary: 'Listed at ₹351 (+33.5% listing gain); 110.9x overall subscription across institutional categories.',
        },
        overallIpoScore: {
          total: 88,
          business: 89,
          financials: 86,
          valuation: 84,
          subscription: 92,
          gmpSupport: 90,
          marketSector: 88,
          riskLevel: 'Low',
        },
      },
      quality: {
        source: 'BSE & NSE Official Trade Engine',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
    },
    {
      id: 'ipo-krn-heat',
      symbol: 'KRN',
      companyName: 'KRN Heat Exchanger and Refrigeration Limited',
      ipoType: 'MAINBOARD',
      openDate: '2024-09-25',
      closeDate: '2024-09-27',
      listingDate: '2024-10-03',
      priceBandMin: 209,
      priceBandMax: 220,
      lotSize: 65,
      minInvestment: 14300,
      issueSizeCr: 341.95,
      freshIssueCr: 341.95,
      ofsCr: 0,
      faceValue: 10,
      status: 'LISTED',
      subscriptions: [
        { category: 'QIB', sharesOffered: 2600000, sharesBid: 657800000, timesSubscribed: 253.0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 1950000, sharesBid: 844350000, timesSubscribed: 433.0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 4550000, sharesBid: 436800000, timesSubscribed: 96.0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 9100000, sharesBid: 1951000000, timesSubscribed: 214.4, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-krn',
        ipoId: 'ipo-krn-heat',
        gmpValue: 260,
        previousGmp: 235,
        trend: 'UP',
        changeAmount: 25,
        estimatedListingPrice: 480,
        estimatedPremiumPercent: 118.18,
        observedAt: nowIso,
        source: 'NSE / BSE Official Listing',
        sourceConfidence: 100,
      },
      gmpHistory: [],
      scores: {
        demandScore: 99,
        gmpSupportScore: {
          score: 99,
          category: 'Strong Positive Support',
          summary: 'Massive multibagger debut: listed at ₹480 (+118.2% premium) on huge 214.4x total subscription.',
        },
        overallIpoScore: {
          total: 95,
          business: 94,
          financials: 92,
          valuation: 89,
          subscription: 99,
          gmpSupport: 99,
          marketSector: 96,
          riskLevel: 'Low',
        },
      },
      quality: {
        source: 'National Stock Exchange (NSE)',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
    },
    {
      id: 'ipo-godavari-bioref',
      symbol: 'GODAVARI',
      companyName: 'Godavari Biorefineries Limited',
      ipoType: 'MAINBOARD',
      openDate: '2024-10-23',
      closeDate: '2024-10-25',
      listingDate: '2024-10-30',
      priceBandMin: 334,
      priceBandMax: 352,
      lotSize: 42,
      minInvestment: 14784,
      issueSizeCr: 554.75,
      freshIssueCr: 325.0,
      ofsCr: 229.75,
      faceValue: 10,
      status: 'UPCOMING',
      subscriptions: [
        { category: 'QIB', sharesOffered: 4500000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 3375000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 7875000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 15750000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-godavari',
        ipoId: 'ipo-godavari-bioref',
        gmpValue: 25,
        previousGmp: 20,
        trend: 'UP',
        changeAmount: 5,
        estimatedListingPrice: 377,
        estimatedPremiumPercent: 7.1,
        observedAt: nowIso,
        source: 'Grey Market Indicative Desk',
        sourceConfidence: 86,
      },
      gmpHistory: [],
      scores: {
        demandScore: 78,
        gmpSupportScore: {
          score: 75,
          category: 'Positive Support',
          summary: 'Integrated bio-refinery producing ethanol, bio-based chemicals, and power; steady industrial demand.',
        },
        overallIpoScore: {
          total: 78,
          business: 82,
          financials: 76,
          valuation: 74,
          subscription: 75,
          gmpSupport: 75,
          marketSector: 82,
          riskLevel: 'Medium',
        },
      },
      quality: {
        source: 'SEBI Approved RHP Prospectus',
        sourceType: 'exchange_filing',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 97,
        status: 'verified',
      },
    },

    // ====================================================
    // 2. SME IPOS (REAL & ACTIVE NSE SME / BSE SME ISSUES)
    // ====================================================
    {
      id: 'ipo-sme-danish-power',
      symbol: 'DANISH',
      companyName: 'Danish Power Limited',
      ipoType: 'SME',
      openDate: '2024-10-22',
      closeDate: '2024-10-24',
      listingDate: '2024-10-29',
      priceBandMin: 360,
      priceBandMax: 380,
      lotSize: 300,
      minInvestment: 114000,
      issueSizeCr: 197.9,
      freshIssueCr: 197.9,
      ofsCr: 0,
      faceValue: 10,
      status: 'OPEN',
      subscriptions: [
        { category: 'QIB', sharesOffered: 1040000, sharesBid: 39936000, timesSubscribed: 38.4, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 780000, sharesBid: 113256000, timesSubscribed: 145.2, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 1820000, sharesBid: 161252000, timesSubscribed: 88.6, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 3640000, sharesBid: 373100000, timesSubscribed: 102.5, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-danish',
        ipoId: 'ipo-sme-danish-power',
        gmpValue: 240,
        previousGmp: 215,
        trend: 'UP',
        changeAmount: 25,
        estimatedListingPrice: 620,
        estimatedPremiumPercent: 63.16,
        observedAt: nowIso,
        source: 'NSE SME Indicative Desk',
        sourceConfidence: 93,
      },
      gmpHistory: [
        {
          id: 'gmp-d-1',
          ipoId: 'ipo-sme-danish-power',
          gmpValue: 190,
          trend: 'UP',
          changeAmount: 0,
          estimatedListingPrice: 570,
          estimatedPremiumPercent: 50.0,
          observedAt: '2024-10-19T10:00:00.000Z',
          source: 'Grey Market Indicative Desk',
          sourceConfidence: 88,
        },
        {
          id: 'gmp-d-2',
          ipoId: 'ipo-sme-danish-power',
          gmpValue: 215,
          previousGmp: 190,
          trend: 'UP',
          changeAmount: 25,
          estimatedListingPrice: 595,
          estimatedPremiumPercent: 56.58,
          observedAt: '2024-10-21T12:00:00.000Z',
          source: 'Grey Market Indicative Desk',
          sourceConfidence: 91,
        },
        {
          id: 'gmp-d-3',
          ipoId: 'ipo-sme-danish-power',
          gmpValue: 240,
          previousGmp: 215,
          trend: 'UP',
          changeAmount: 25,
          estimatedListingPrice: 620,
          estimatedPremiumPercent: 63.16,
          observedAt: nowIso,
          source: 'Grey Market Indicative Desk',
          sourceConfidence: 93,
        },
      ],
      scores: {
        demandScore: 94,
        gmpSupportScore: {
          score: 93,
          category: 'Strong Positive Support',
          summary: 'Huge ~63% GMP premium; top transformer manufacturer benefiting from India’s renewable grid transmission expansion.',
        },
        overallIpoScore: {
          total: 91,
          business: 92,
          financials: 90,
          valuation: 85,
          subscription: 94,
          gmpSupport: 93,
          marketSector: 95,
          riskLevel: 'Low',
        },
      },
      quality: {
        source: 'NSE Emerge SME Platform',
        sourceType: 'exchange_filing',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 99,
        status: 'verified',
      },
    },
    {
      id: 'ipo-sme-united-heat',
      symbol: 'UHTL',
      companyName: 'United Heat Transfer Limited',
      ipoType: 'SME',
      openDate: '2024-10-22',
      closeDate: '2024-10-24',
      listingDate: '2024-10-29',
      priceBandMin: 56,
      priceBandMax: 59,
      lotSize: 2000,
      minInvestment: 118000,
      issueSizeCr: 29.97,
      freshIssueCr: 29.97,
      ofsCr: 0,
      faceValue: 10,
      status: 'OPEN',
      subscriptions: [
        { category: 'QIB', sharesOffered: 960000, sharesBid: 11520000, timesSubscribed: 12.0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 720000, sharesBid: 34920000, timesSubscribed: 48.5, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 1680000, sharesBid: 54432000, timesSubscribed: 32.4, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 3360000, sharesBid: 114912000, timesSubscribed: 34.2, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-uhtl',
        ipoId: 'ipo-sme-united-heat',
        gmpValue: 28,
        previousGmp: 24,
        trend: 'UP',
        changeAmount: 4,
        estimatedListingPrice: 87,
        estimatedPremiumPercent: 47.46,
        observedAt: nowIso,
        source: 'NSE SME Platform',
        sourceConfidence: 90,
      },
      gmpHistory: [],
      scores: {
        demandScore: 86,
        gmpSupportScore: {
          score: 88,
          category: 'Strong Positive Support',
          summary: 'Solid 47.5% premium for heat exchangers and shell-and-tube units for marine, naval, and power industries.',
        },
        overallIpoScore: {
          total: 85,
          business: 86,
          financials: 84,
          valuation: 82,
          subscription: 86,
          gmpSupport: 88,
          marketSector: 88,
          riskLevel: 'Medium',
        },
      },
      quality: {
        source: 'NSE Emerge SME Platform',
        sourceType: 'exchange_filing',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 98,
        status: 'verified',
      },
    },
    {
      id: 'ipo-sme-obsc-perfection',
      symbol: 'OBSC',
      companyName: 'OBSC Perfection Limited',
      ipoType: 'SME',
      openDate: '2024-10-22',
      closeDate: '2024-10-24',
      listingDate: '2024-10-29',
      priceBandMin: 95,
      priceBandMax: 100,
      lotSize: 1200,
      minInvestment: 120000,
      issueSizeCr: 66.02,
      freshIssueCr: 66.02,
      ofsCr: 0,
      faceValue: 10,
      status: 'UPCOMING',
      subscriptions: [
        { category: 'QIB', sharesOffered: 1250000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 940000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 2190000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 4380000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-obsc',
        ipoId: 'ipo-sme-obsc-perfection',
        gmpValue: 35,
        previousGmp: 30,
        trend: 'UP',
        changeAmount: 5,
        estimatedListingPrice: 135,
        estimatedPremiumPercent: 35.0,
        observedAt: nowIso,
        source: 'NSE SME Platform',
        sourceConfidence: 89,
      },
      gmpHistory: [],
      scores: {
        demandScore: 82,
        gmpSupportScore: {
          score: 83,
          category: 'Positive Support',
          summary: 'Precision metal component manufacturer for automotive OEM giants including Tata Motors and Mahindra.',
        },
        overallIpoScore: {
          total: 82,
          business: 84,
          financials: 82,
          valuation: 78,
          subscription: 80,
          gmpSupport: 83,
          marketSector: 85,
          riskLevel: 'Medium',
        },
      },
      quality: {
        source: 'NSE Emerge SME Platform',
        sourceType: 'exchange_filing',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 98,
        status: 'verified',
      },
    },
    {
      id: 'ipo-sme-usha-fin',
      symbol: 'USHAFIN',
      companyName: 'Usha Financial Services Limited',
      ipoType: 'SME',
      openDate: '2024-10-24',
      closeDate: '2024-10-28',
      listingDate: '2024-10-31',
      priceBandMin: 160,
      priceBandMax: 168,
      lotSize: 800,
      minInvestment: 134400,
      issueSizeCr: 98.45,
      freshIssueCr: 98.45,
      ofsCr: 0,
      faceValue: 10,
      status: 'UPCOMING',
      subscriptions: [
        { category: 'QIB', sharesOffered: 1120000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 840000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 1960000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 3920000, sharesBid: 0, timesSubscribed: 0, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-usha',
        ipoId: 'ipo-sme-usha-fin',
        gmpValue: 42,
        previousGmp: 35,
        trend: 'UP',
        changeAmount: 7,
        estimatedListingPrice: 210,
        estimatedPremiumPercent: 25.0,
        observedAt: nowIso,
        source: 'NSE SME Platform',
        sourceConfidence: 87,
      },
      gmpHistory: [],
      scores: {
        demandScore: 80,
        gmpSupportScore: {
          score: 80,
          category: 'Positive Support',
          summary: 'Non-banking finance company catering to MSMEs, corporates, and retail loans with 30%+ AUM growth.',
        },
        overallIpoScore: {
          total: 80,
          business: 82,
          financials: 80,
          valuation: 76,
          subscription: 78,
          gmpSupport: 80,
          marketSector: 82,
          riskLevel: 'Medium',
        },
      },
      quality: {
        source: 'NSE Emerge SME Platform',
        sourceType: 'exchange_filing',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 97,
        status: 'verified',
      },
    },
    {
      id: 'ipo-sme-rappid-valves',
      symbol: 'RAPPID',
      companyName: 'Rappid Valves (India) Limited',
      ipoType: 'SME',
      openDate: '2024-09-23',
      closeDate: '2024-09-25',
      listingDate: '2024-09-30',
      priceBandMin: 210,
      priceBandMax: 222,
      lotSize: 600,
      minInvestment: 133200,
      issueSizeCr: 30.41,
      freshIssueCr: 30.41,
      ofsCr: 0,
      faceValue: 10,
      status: 'LISTED',
      subscriptions: [
        { category: 'QIB', sharesOffered: 260000, sharesBid: 42120000, timesSubscribed: 162.0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 195000, sharesBid: 96525000, timesSubscribed: 495.0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 455000, sharesBid: 47775000, timesSubscribed: 105.0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 910000, sharesBid: 165620000, timesSubscribed: 182.0, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-rappid',
        ipoId: 'ipo-sme-rappid-valves',
        gmpValue: 90,
        previousGmp: 85,
        trend: 'UP',
        changeAmount: 5,
        estimatedListingPrice: 312,
        estimatedPremiumPercent: 40.54,
        observedAt: nowIso,
        source: 'BSE SME Official Listing',
        sourceConfidence: 100,
      },
      gmpHistory: [],
      scores: {
        demandScore: 95,
        gmpSupportScore: {
          score: 94,
          category: 'Strong Positive Support',
          summary: 'Listed at ₹312 (+40.5% premium) on massive 182x overall subscription for industrial valve manufacturing.',
        },
        overallIpoScore: {
          total: 90,
          business: 89,
          financials: 88,
          valuation: 85,
          subscription: 95,
          gmpSupport: 94,
          marketSector: 90,
          riskLevel: 'Low',
        },
      },
      quality: {
        source: 'BSE SME Trade Engine',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
    },
    {
      id: 'ipo-sme-wol-3d',
      symbol: 'WOL3D',
      companyName: 'WOL 3D India Limited',
      ipoType: 'SME',
      openDate: '2024-09-23',
      closeDate: '2024-09-25',
      listingDate: '2024-09-30',
      priceBandMin: 142,
      priceBandMax: 150,
      lotSize: 1000,
      minInvestment: 150000,
      issueSizeCr: 25.56,
      freshIssueCr: 25.56,
      ofsCr: 0,
      faceValue: 10,
      status: 'LISTED',
      subscriptions: [
        { category: 'QIB', sharesOffered: 240000, sharesBid: 24000000, timesSubscribed: 100.0, updatedAt: nowIso },
        { category: 'NII', sharesOffered: 180000, sharesBid: 68400000, timesSubscribed: 380.0, updatedAt: nowIso },
        { category: 'Retail', sharesOffered: 420000, sharesBid: 35700000, timesSubscribed: 85.0, updatedAt: nowIso },
        { category: 'Total', sharesOffered: 840000, sharesBid: 128100000, timesSubscribed: 152.5, updatedAt: nowIso },
      ],
      latestGmp: {
        id: 'gmp-wol3d',
        ipoId: 'ipo-sme-wol-3d',
        gmpValue: 35,
        previousGmp: 30,
        trend: 'UP',
        changeAmount: 5,
        estimatedListingPrice: 185,
        estimatedPremiumPercent: 23.33,
        observedAt: nowIso,
        source: 'NSE SME Official Listing',
        sourceConfidence: 100,
      },
      gmpHistory: [],
      scores: {
        demandScore: 92,
        gmpSupportScore: {
          score: 88,
          category: 'Positive Support',
          summary: 'Listed at ₹185 (+23.3% premium); pioneer in consumer and industrial 3D printing equipment in India.',
        },
        overallIpoScore: {
          total: 87,
          business: 86,
          financials: 85,
          valuation: 82,
          subscription: 92,
          gmpSupport: 88,
          marketSector: 90,
          riskLevel: 'Low',
        },
      },
      quality: {
        source: 'NSE Emerge SME Platform',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
    },
  ];
}
