import { StockQuote, Fundamentals, ValuationMetrics, ShareholdingQuarter } from '../../src/types/index.ts';

export function getSeedStocks(nowIso: string): StockQuote[] {
  return [
    {
      symbol: 'TRENT',
      companyName: 'Trent Limited',
      isin: 'INE849A01020',
      sector: 'Consumer Discretionary',
      industry: 'Retail - Apparel & Specialty',
      price: 2631.2,
      change: -36.8,
      percentChange: -1.38,
      volume: 2480000,
      averageVolume30D: 1850000,
      relativeVolume: 1.34,
      marketCapCr: 93500,
      capCategory: 'Large Cap',
      high52Week: 2850,
      low52Week: 1250,
      openPrice: 2660,
      previousClose: 2669.3,
      dayHigh: 2663.8,
      dayLow: 2616.4,
      quality: {
        source: 'NSE Real-time Trade Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
      catalyst: 'Strong Zudio and Westside same-store sales growth and continued store rollouts',
    },
    {
      symbol: 'POLYCAB',
      companyName: 'Polycab India Limited',
      isin: 'INE455K01017',
      sector: 'Industrials',
      industry: 'Electrical Equipment & Cables',
      price: 8206.0,
      change: -202.5,
      percentChange: -2.41,
      volume: 980000,
      averageVolume30D: 820000,
      relativeVolume: 1.19,
      marketCapCr: 123400,
      capCategory: 'Large Cap',
      high52Week: 8550,
      low52Week: 4650,
      openPrice: 8350,
      previousClose: 8408.5,
      dayHigh: 8400,
      dayLow: 8201.5,
      quality: {
        source: 'NSE Real-time Trade Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
      catalyst: 'Infrastructure tailwinds, smart metering demand, and domestic real-estate wire volumes',
    },
    {
      symbol: 'KAYNES',
      companyName: 'Kaynes Technology India Limited',
      isin: 'INE918Z01012',
      sector: 'Information Technology',
      industry: 'Electronic Manufacturing Services (EMS)',
      price: 3637.8,
      change: -12.2,
      percentChange: -0.33,
      volume: 720000,
      averageVolume30D: 650000,
      relativeVolume: 1.11,
      marketCapCr: 23200,
      capCategory: 'Mid Cap',
      high52Week: 3950,
      low52Week: 1820,
      openPrice: 3650,
      previousClose: 3650,
      dayHigh: 3658,
      dayLow: 3589,
      quality: {
        source: 'NSE Real-time Trade Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
      catalyst: 'OSAT semiconductor packaging plant expansion and railway signaling order book',
    },
    {
      symbol: 'CDSL',
      companyName: 'Central Depository Services Limited',
      isin: 'INE736A01011',
      sector: 'Financials',
      industry: 'Capital Markets Infrastructure',
      price: 1300.7,
      change: -17.3,
      percentChange: -1.31,
      volume: 4800000,
      averageVolume30D: 3900000,
      relativeVolume: 1.23,
      marketCapCr: 27200,
      capCategory: 'Mid Cap',
      high52Week: 1450,
      low52Week: 720,
      openPrice: 1315,
      previousClose: 1318,
      dayHigh: 1318,
      dayLow: 1294,
      quality: {
        source: 'NSE Real-time Trade Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
      catalyst: 'Record pace of Indian retail demat account additions exceeding 17 crore accounts',
    },
    {
      symbol: 'TATAMOTORS',
      companyName: 'Tata Motors Limited',
      isin: 'INE155A01022',
      sector: 'Consumer Discretionary',
      industry: 'Automobile Manufacturers',
      price: 283.7,
      change: -6.75,
      percentChange: -2.32,
      volume: 8500000,
      averageVolume30D: 10200000,
      relativeVolume: 0.83,
      marketCapCr: 212000,
      capCategory: 'Large Cap',
      high52Week: 350,
      low52Week: 190,
      openPrice: 288,
      previousClose: 290.45,
      dayHigh: 289.5,
      dayLow: 282.8,
      quality: {
        source: 'NSE Real-time Trade Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
      catalyst: 'Demerger into Commercial Vehicles & Passenger Vehicles unlocking shareholder value',
    },
    {
      symbol: 'KPITTECH',
      companyName: 'KPIT Technologies Limited',
      isin: 'INE04QT01022',
      sector: 'Information Technology',
      industry: 'Automotive Software & ER&D',
      price: 512.0,
      change: -7.4,
      percentChange: -1.42,
      volume: 1650000,
      averageVolume30D: 1400000,
      relativeVolume: 1.18,
      marketCapCr: 39500,
      capCategory: 'Mid Cap',
      high52Week: 620,
      low52Week: 340,
      openPrice: 518,
      previousClose: 519.4,
      dayHigh: 519,
      dayLow: 508.25,
      quality: {
        source: 'NSE Real-time Trade Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
      catalyst: 'Software-defined vehicle (SDV) architectural multi-year programs with tier-1 global OEMs',
    },
    {
      symbol: 'ICICIBANK',
      companyName: 'ICICI Bank Limited',
      isin: 'INE090A01021',
      sector: 'Financials',
      industry: 'Private Commercial Banking',
      price: 1305.2,
      change: -21.6,
      percentChange: -1.63,
      volume: 8900000,
      averageVolume30D: 9400000,
      relativeVolume: 0.95,
      marketCapCr: 918000,
      capCategory: 'Large Cap',
      high52Week: 1360,
      low52Week: 935,
      openPrice: 1318,
      previousClose: 1326.8,
      dayHigh: 1323.8,
      dayLow: 1300.6,
      quality: {
        source: 'NSE Real-time Trade Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
      catalyst: 'Industry-leading Return on Equity (18.7%) with low credit costs and digital banking market share',
    },
    {
      symbol: 'ITC',
      companyName: 'ITC Limited',
      isin: 'INE154A01025',
      sector: 'Consumer Staples',
      industry: 'Diversified FMCG & Cigarettes',
      price: 266.3,
      change: -2.7,
      percentChange: -1.0,
      volume: 12400000,
      averageVolume30D: 14200000,
      relativeVolume: 0.87,
      marketCapCr: 334000,
      capCategory: 'Large Cap',
      high52Week: 310,
      low52Week: 235,
      openPrice: 268.5,
      previousClose: 269,
      dayHigh: 269.3,
      dayLow: 265.25,
      quality: {
        source: 'NSE Real-time Trade Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
      catalyst: 'Hotel business demerger listing progress and steady FMCG-Others EBIT margin expansion',
    },
    {
      symbol: 'DIXON',
      companyName: 'Dixon Technologies (India) Limited',
      isin: 'INE935N01020',
      sector: 'Industrials',
      industry: 'Consumer Electronics & Mobile EMS',
      price: 13556.0,
      change: 166.0,
      percentChange: 1.24,
      volume: 890000,
      averageVolume30D: 740000,
      relativeVolume: 1.2,
      marketCapCr: 81200,
      capCategory: 'Large Cap',
      high52Week: 14200,
      low52Week: 5200,
      openPrice: 13420,
      previousClose: 13390,
      dayHigh: 13593,
      dayLow: 13234,
      quality: {
        source: 'NSE Real-time Trade Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
      catalyst: 'Smartphone PLI assembly ramp-up, Ismartu acquisition integration, and display module manufacturing',
    },
    {
      symbol: 'SUZLON',
      companyName: 'Suzlon Energy Limited',
      isin: 'INE040H01021',
      sector: 'Energy',
      industry: 'Wind Turbine Generator (WTG) Manufacturing',
      price: 39.93,
      change: -0.87,
      percentChange: -2.13,
      volume: 38000000,
      averageVolume30D: 45000000,
      relativeVolume: 0.84,
      marketCapCr: 54500,
      capCategory: 'Mid Cap',
      high52Week: 55,
      low52Week: 24,
      openPrice: 40.5,
      previousClose: 40.8,
      dayHigh: 40.93,
      dayLow: 39.83,
      quality: {
        source: 'NSE Real-time Trade Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
      catalyst: 'Net debt-free balance sheet with multi-gigawatt commercial & industrial order backlog',
    },
    {
      symbol: 'BHARTIARTL',
      companyName: 'Bharti Airtel Limited',
      isin: 'INE397D01024',
      sector: 'Communication Services',
      industry: 'Telecom Carrier Services',
      price: 1777.1,
      change: -8.3,
      percentChange: -0.46,
      volume: 5200000,
      averageVolume30D: 5900000,
      relativeVolume: 0.88,
      marketCapCr: 1045000,
      capCategory: 'Large Cap',
      high52Week: 1840,
      low52Week: 990,
      openPrice: 1782,
      previousClose: 1785.4,
      dayHigh: 1779,
      dayLow: 1763.7,
      quality: {
        source: 'NSE Real-time Trade Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
      catalyst: 'Industry tariff repair flow-through driving ARPU towards ₹230+ with strong 5G FWA additions',
    },
    {
      symbol: 'INFY',
      companyName: 'Infosys Limited',
      isin: 'INE009A01021',
      sector: 'Information Technology',
      industry: 'IT Services & Enterprise Consulting',
      price: 1000.0,
      change: -0.2,
      percentChange: -0.02,
      volume: 6800000,
      averageVolume30D: 7200000,
      relativeVolume: 0.94,
      marketCapCr: 795000,
      capCategory: 'Large Cap',
      high52Week: 1120,
      low52Week: 780,
      openPrice: 998,
      previousClose: 1000.2,
      dayHigh: 1004.2,
      dayLow: 986.6,
      quality: {
        source: 'NSE Real-time Trade Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
      catalyst: 'Large mega-deal pipeline and enterprise deployment of Infosys Topaz GenAI platform',
    },
    {
      symbol: 'RELIANCE',
      companyName: 'Reliance Industries Limited',
      isin: 'INE002A01018',
      sector: 'Energy',
      industry: 'Oil to Chemicals, Retail & Telecom',
      price: 1208.2,
      change: -17.8,
      percentChange: -1.45,
      volume: 5900000,
      averageVolume30D: 6400000,
      relativeVolume: 0.92,
      marketCapCr: 1635000,
      capCategory: 'Large Cap',
      high52Week: 1611,
      low52Week: 1205,
      openPrice: 1218,
      previousClose: 1226,
      dayHigh: 1219.7,
      dayLow: 1205.4,
      quality: {
        source: 'NSE Real-time Trade Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
      catalyst: 'New Energy giga-factories commissioning and Jio digital subscriber growth monetization',
    },
    {
      symbol: 'HDFCBANK',
      companyName: 'HDFC Bank Limited',
      isin: 'INE040A01034',
      sector: 'Financials',
      industry: 'Private Commercial Banking',
      price: 722.05,
      change: -13.55,
      percentChange: -1.84,
      volume: 14800000,
      averageVolume30D: 16200000,
      relativeVolume: 0.91,
      marketCapCr: 1105000,
      capCategory: 'Large Cap',
      high52Week: 820,
      low52Week: 670,
      openPrice: 730,
      previousClose: 735.6,
      dayHigh: 733,
      dayLow: 720,
      quality: {
        source: 'NSE Real-time Trade Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
      catalyst: 'Post-merger loan-to-deposit ratio (LDR) normalisation and branch deposit accretion',
    },
    {
      symbol: 'SUNPHARMA',
      companyName: 'Sun Pharmaceutical Industries Limited',
      isin: 'INE044A01036',
      sector: 'Healthcare',
      industry: 'Pharmaceuticals & Global Specialty Formulations',
      price: 1842.6,
      change: -9.6,
      percentChange: -0.52,
      volume: 1950000,
      averageVolume30D: 2200000,
      relativeVolume: 0.89,
      marketCapCr: 442000,
      capCategory: 'Large Cap',
      high52Week: 1920,
      low52Week: 1180,
      openPrice: 1850,
      previousClose: 1852.2,
      dayHigh: 1855,
      dayLow: 1839.1,
      quality: {
        source: 'NSE Real-time Trade Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
      catalyst: 'Global innovative specialty franchise growth (Ilumya, Cequa, Winlevi) driving high gross margins',
    },
    {
      symbol: 'TCS',
      companyName: 'Tata Consultancy Services Limited',
      isin: 'INE467B01029',
      sector: 'Information Technology',
      industry: 'IT Services & Consulting',
      price: 2073.9,
      change: -8.1,
      percentChange: -0.39,
      volume: 1850000,
      averageVolume30D: 2100000,
      relativeVolume: 0.88,
      marketCapCr: 1485000,
      capCategory: 'Large Cap',
      high52Week: 2315,
      low52Week: 1680,
      openPrice: 2085,
      previousClose: 2082,
      dayHigh: 2100,
      dayLow: 2051,
      quality: {
        source: 'NSE Real-time Trade Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
      catalyst: 'Record $11.2B order book and multi-year AI enterprise transformation deals',
    },
    {
      symbol: 'LT',
      companyName: 'Larsen & Toubro Limited',
      isin: 'INE018A01030',
      sector: 'Industrials',
      industry: 'Heavy Engineering & Infrastructure EPC',
      price: 3791.8,
      change: -84.4,
      percentChange: -2.18,
      volume: 1420000,
      averageVolume30D: 1650000,
      relativeVolume: 0.86,
      marketCapCr: 521000,
      capCategory: 'Large Cap',
      high52Week: 3950,
      low52Week: 2850,
      openPrice: 3840,
      previousClose: 3876.2,
      dayHigh: 3858.2,
      dayLow: 3790,
      quality: {
        source: 'NSE Real-time Trade Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
      catalyst: 'Mega domestic infrastructure capex and international Middle East hydrocarbon order flows',
    },
    {
      symbol: 'SBIN',
      companyName: 'State Bank of India',
      isin: 'INE062A01020',
      sector: 'Financials',
      industry: 'Public Sector Banking',
      price: 965.0,
      change: -18.0,
      percentChange: -1.83,
      volume: 14500000,
      averageVolume30D: 18200000,
      relativeVolume: 0.8,
      marketCapCr: 861000,
      capCategory: 'Large Cap',
      high52Week: 998,
      low52Week: 555,
      openPrice: 978,
      previousClose: 983,
      dayHigh: 982.5,
      dayLow: 963.3,
      quality: {
        source: 'NSE Real-time Trade Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
      catalyst: 'Record quarterly return on assets (RoA 1.05%) and lowest net NPA in a decade (0.57%)',
    },
    {
      symbol: 'HCLTECH',
      companyName: 'HCL Technologies Limited',
      isin: 'INE860A01027',
      sector: 'Information Technology',
      industry: 'IT Services & Consulting',
      price: 1249.2,
      change: -8.8,
      percentChange: -0.7,
      volume: 2450000,
      averageVolume30D: 2800000,
      relativeVolume: 0.87,
      marketCapCr: 338000,
      capCategory: 'Large Cap',
      high52Week: 1320,
      low52Week: 920,
      openPrice: 1255,
      previousClose: 1258,
      dayHigh: 1263,
      dayLow: 1241.8,
      quality: {
        source: 'NSE Real-time Trade Feed',
        sourceType: 'official_feed',
        observedAt: nowIso,
        retrievedAt: nowIso,
        confidence: 100,
        status: 'verified',
      },
      catalyst: 'Industry-leading digital engineering services growth and GenAI software platform adoptions',
    },
  ];
}
